# CodeTank upper-bank dispatcher menu (128 B at $4000)
PROJECT  := codetank_menu_upper
LOAD_CFG := apple1_codetank_menu_upper.cfg
OUT_DIR  := ../../../software/tms9918
LIB      := -I ../../lib/apple1

include ../../cc65/Makefile.common
