# HGR5 House
PROJECT  := HGR5_House
LOAD_CFG := ../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../software/hgr
LIB      := -I ../../lib/apple1 -I ../../lib/hgr -I ../../lib/m6502

include ../../cc65/Makefile.common
