# HGR2 Sierpinski
PROJECT  := HGR2_Sierpinski
LOAD_CFG := ../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../software/hgr
LIB      := -I ../../lib/apple1 -I ../../lib/hgr

include ../../cc65/Makefile.common
