# HGR House
PROJECT  := HGR_House
LOAD_CFG := ../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../software/hgr
LIB      := -I ../../lib/apple1 -I ../../lib/hgr -I ../../lib/m6502
EMIT_TXT := 1

include ../../cc65/Makefile.common
