# TMS9918 Connect 4
PROJECT  := TMS_Connect4
LOAD_CFG := ../../cc65/apple1.cfg
OUT_DIR  := ../../../software/tms9918
LIB      := -I ../../lib/apple1 -I ../../lib/tms9918

include ../../cc65/Makefile.common
