# TMS9918 Connect 4
PROJECT  := TMS_Connect4
LOAD_CFG := ../../cc65/apple1_4k.cfg
OUT_DIR  := ../../../software/Graphic TMS9918
LIB      := -I ../../lib/apple1 -I ../../lib/tms9918
EXTRA_ASM := ../../lib/tms9918/tms9918_pad.asm

include ../../cc65/Makefile.common
