; ============================================================================
; sprites_exploration_hgr.asm  --  21 sprites in GEN2 HGR format
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "Exploration" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_exploration.asm. Do not edit by hand —
; rerun the tool to refresh after changing the TMS source.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte; bit 7 stays
; clear (NTSC group selector). 16-px sprite occupies cols 0..6
; in byte 0, cols 7..13 in byte 1, cols 14..15 in bits 0..1 of
; byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export expl_torch_pat, expl_lantern_pat, expl_bomb_pat, expl_pickaxe_pat, expl_rope_pat
.export expl_flask_pat, expl_coin_pat, expl_chest_closed_pat, expl_chest_open_pat, expl_mortar_pat
.export expl_key_small_pat, expl_key_pat, expl_lock_pat, expl_book_pat, expl_compass_pat
.export expl_scroll_pat, expl_clock_pat, expl_poison_pat, expl_bone_pat, expl_shell_pat
.export expl_mask_pat
.export exploration_hgr_data

; Constants like EXPLORATION_HGR_COUNT live in the sister
; sprites_exploration_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

exploration_hgr_data:
; slot 01/21 of "Exploration" row -- torch
expl_torch_pat:
        .byte $00, $00, $00, $00, $04, $00, $00, $2C, $00, $20, $1E, $00  ; rows 00..03
        .byte $00, $1E, $00, $00, $3F, $00, $48, $33, $00, $60, $39, $00  ; rows 04..07
        .byte $20, $3C, $00, $40, $1E, $00, $60, $0F, $00, $30, $00, $00  ; rows 08..11
        .byte $18, $00, $00, $0C, $00, $00, $06, $00, $00, $00, $00, $00  ; rows 12..15
; slot 02/21 of "Exploration" row -- lantern
expl_lantern_pat:
        .byte $00, $00, $00, $40, $07, $00, $40, $04, $00, $20, $0B, $00  ; rows 00..03
        .byte $30, $18, $00, $74, $5F, $00, $60, $0F, $00, $00, $00, $00  ; rows 04..07
        .byte $66, $4F, $01, $60, $0F, $00, $60, $0F, $00, $54, $57, $00  ; rows 08..11
        .byte $30, $18, $00, $60, $0F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 03/21 of "Exploration" row -- bomb
expl_bomb_pat:
        .byte $00, $00, $00, $00, $30, $00, $00, $50, $00, $00, $10, $01  ; rows 00..03
        .byte $00, $78, $01, $00, $1C, $00, $00, $0E, $00, $10, $07, $00  ; rows 04..07
        .byte $38, $03, $00, $3C, $00, $00, $7E, $01, $00, $7E, $03, $00  ; rows 08..11
        .byte $7E, $01, $00, $7E, $00, $00, $3E, $00, $00, $00, $00, $00  ; rows 12..15
; slot 04/21 of "Exploration" row -- pickaxe
expl_pickaxe_pat:
        .byte $00, $00, $00, $70, $03, $00, $00, $6F, $00, $00, $7C, $00  ; rows 00..03
        .byte $00, $38, $00, $00, $70, $00, $00, $66, $00, $00, $47, $01  ; rows 04..07
        .byte $40, $43, $01, $60, $01, $01, $70, $00, $01, $38, $00, $01  ; rows 08..11
        .byte $1C, $00, $00, $0E, $00, $00, $06, $00, $00, $00, $00, $00  ; rows 12..15
; slot 05/21 of "Exploration" row -- rope
expl_rope_pat:
        .byte $00, $00, $00, $00, $1E, $00, $00, $21, $00, $02, $21, $00  ; rows 00..03
        .byte $04, $21, $00, $04, $12, $00, $04, $1E, $00, $04, $06, $00  ; rows 04..07
        .byte $44, $1E, $00, $24, $00, $00, $24, $12, $00, $24, $21, $00  ; rows 08..11
        .byte $18, $21, $00, $00, $21, $00, $00, $1E, $00, $00, $00, $00  ; rows 12..15
; slot 06/21 of "Exploration" row -- flask
expl_flask_pat:
        .byte $00, $00, $00, $00, $18, $00, $00, $24, $00, $00, $23, $00  ; rows 00..03
        .byte $00, $24, $00, $70, $23, $00, $78, $44, $00, $7C, $09, $00  ; rows 04..07
        .byte $7C, $09, $00, $74, $08, $00, $04, $08, $00, $04, $08, $00  ; rows 08..11
        .byte $08, $04, $00, $70, $03, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 07/21 of "Exploration" row -- coin
expl_coin_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $7C, $37, $00, $7E, $7B, $00, $4E, $7B, $00, $10, $00, $00  ; rows 04..07
        .byte $5E, $7B, $00, $4E, $7B, $00, $7E, $7B, $00, $7E, $7B, $00  ; rows 08..11
        .byte $7E, $7B, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 08/21 of "Exploration" row -- chest_closed
expl_chest_closed_pat:
        .byte $00, $00, $00, $00, $00, $00, $60, $75, $00, $20, $40, $01  ; rows 00..03
        .byte $20, $40, $01, $20, $40, $01, $20, $40, $01, $4E, $7B, $00  ; rows 04..07
        .byte $7E, $7B, $00, $7E, $7B, $00, $7E, $7B, $00, $7E, $7B, $00  ; rows 08..11
        .byte $7E, $7B, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 09/21 of "Exploration" row -- chest_open
expl_chest_open_pat:
        .byte $00, $00, $00, $60, $0F, $00, $10, $10, $00, $10, $13, $00  ; rows 00..03
        .byte $18, $30, $00, $6C, $6F, $00, $1E, $70, $01, $7E, $7F, $01  ; rows 04..07
        .byte $7C, $7F, $00, $7A, $3F, $01, $62, $0F, $01, $14, $50, $00  ; rows 08..11
        .byte $3C, $7B, $00, $78, $3F, $00, $60, $0F, $00, $00, $00, $00  ; rows 12..15
; slot 10/21 of "Exploration" row -- mortar
expl_mortar_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $40, $03, $00  ; rows 00..03
        .byte $00, $1D, $00, $24, $1E, $00, $0E, $40, $01, $60, $40, $01  ; rows 04..07
        .byte $68, $62, $01, $02, $70, $01, $0E, $72, $01, $1E, $6F, $00  ; rows 08..11
        .byte $1C, $1F, $00, $58, $3F, $00, $40, $0F, $00, $00, $00, $00  ; rows 12..15
; slot 11/21 of "Exploration" row -- key_small
expl_key_small_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $38, $00, $00, $7C, $00, $00, $44, $00, $00, $44, $7F, $00  ; rows 04..07
        .byte $44, $7F, $00, $44, $70, $00, $7C, $50, $00, $38, $00, $00  ; rows 08..11
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 12/21 of "Exploration" row -- key
expl_key_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $60, $00, $00, $10, $01, $00, $1C, $01, $00, $72, $7F, $00  ; rows 04..07
        .byte $72, $7F, $00, $1C, $71, $00, $10, $51, $00, $60, $00, $00  ; rows 08..11
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 13/21 of "Exploration" row -- lock
expl_lock_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $60, $07, $00, $30, $0C, $00, $10, $0E, $00, $60, $07, $00  ; rows 04..07
        .byte $10, $08, $00, $58, $1E, $00, $5C, $3E, $00, $1C, $3F, $00  ; rows 08..11
        .byte $7C, $3F, $00, $7C, $1F, $00, $78, $07, $00, $00, $00, $00  ; rows 12..15
; slot 14/21 of "Exploration" row -- book
expl_book_pat:
        .byte $00, $00, $00, $00, $00, $00, $70, $03, $00, $78, $07, $00  ; rows 00..03
        .byte $78, $03, $00, $70, $7D, $00, $08, $7E, $01, $70, $7E, $01  ; rows 04..07
        .byte $00, $7C, $00, $00, $02, $01, $00, $7C, $00, $7C, $02, $01  ; rows 08..11
        .byte $7E, $7D, $00, $7E, $01, $00, $7C, $00, $00, $00, $00, $00  ; rows 12..15
; slot 15/21 of "Exploration" row -- compass
expl_compass_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $60, $0F, $00  ; rows 00..03
        .byte $70, $17, $00, $78, $2F, $00, $78, $2D, $00, $38, $27, $00  ; rows 04..07
        .byte $18, $27, $00, $78, $23, $00, $68, $24, $00, $10, $10, $00  ; rows 08..11
        .byte $60, $0F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 16/21 of "Exploration" row -- scroll
expl_scroll_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $3F, $00  ; rows 00..03
        .byte $40, $3E, $00, $20, $2F, $00, $50, $27, $00, $68, $23, $00  ; rows 04..07
        .byte $68, $21, $00, $68, $10, $00, $08, $08, $00, $08, $04, $00  ; rows 08..11
        .byte $78, $03, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 17/21 of "Exploration" row -- clock
expl_clock_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $60, $0F, $00  ; rows 00..03
        .byte $50, $13, $00, $68, $27, $00, $68, $27, $00, $68, $27, $00  ; rows 04..07
        .byte $68, $27, $00, $48, $23, $00, $08, $20, $00, $10, $10, $00  ; rows 08..11
        .byte $60, $0F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 18/21 of "Exploration" row -- poison
expl_poison_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $1F, $00, $40, $3F, $00  ; rows 00..03
        .byte $00, $33, $00, $00, $33, $00, $40, $1E, $00, $40, $03, $00  ; rows 04..07
        .byte $18, $30, $00, $60, $0C, $00, $00, $03, $00, $60, $0C, $00  ; rows 08..11
        .byte $1C, $70, $00, $0C, $60, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 19/21 of "Exploration" row -- bone
expl_bone_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $00, $00, $00, $00, $60, $00, $0C, $60, $00, $7C, $3F, $00  ; rows 04..07
        .byte $78, $7F, $00, $0C, $60, $00, $0C, $00, $00, $00, $00, $00  ; rows 08..11
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 20/21 of "Exploration" row -- shell
expl_shell_pat:
        .byte $00, $00, $00, $00, $00, $00, $70, $03, $00, $78, $07, $00  ; rows 00..03
        .byte $7C, $0F, $00, $7C, $0C, $00, $3C, $0D, $00, $3C, $17, $00  ; rows 04..07
        .byte $3C, $38, $00, $7C, $3F, $00, $7C, $3F, $00, $78, $3F, $00  ; rows 08..11
        .byte $60, $1F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 21/21 of "Exploration" row -- mask
expl_mask_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $78, $03, $00  ; rows 00..03
        .byte $0C, $1F, $00, $0C, $22, $00, $1C, $26, $00, $78, $3F, $00  ; rows 04..07
        .byte $44, $2A, $00, $1C, $00, $00, $3C, $15, $00, $7C, $3F, $00  ; rows 08..11
        .byte $78, $3F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
