; ============================================================================
; sprites_magick_hgr.asm  --  15 sprites in GEN2 HGR format
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "Magick" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_magick.asm. Do not edit by hand —
; rerun the tool to refresh after changing the TMS source.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte; bit 7 stays
; clear (NTSC group selector). 16-px sprite occupies cols 0..6
; in byte 0, cols 7..13 in byte 1, cols 14..15 in bits 0..1 of
; byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export magic_wand_pat, magic_wand_orb_pat, magic_wand_skull_pat, magic_orb_pat, magic_ankh_pat
.export magic_effigy_pat, magic_scroll_pat, magic_scroll_open_pat, magic_runestone_pat, magic_book_pat
.export magic_mirror_pat, magic_vortex_pat, magic_portal_pat, magic_hand_pat, magic_sun_pat
.export magick_hgr_data

; Constants like MAGICK_HGR_COUNT live in the sister
; sprites_magick_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

magick_hgr_data:
; slot 01/15 of "Magick" row -- wand
magic_wand_pat:
        .byte $00, $00, $00, $00, $20, $00, $00, $01, $00, $00, $3C, $00  ; rows 00..03
        .byte $00, $7E, $00, $20, $46, $00, $00, $5B, $00, $00, $6B, $00  ; rows 04..07
        .byte $40, $3B, $00, $60, $01, $01, $70, $00, $00, $38, $08, $00  ; rows 08..11
        .byte $1C, $00, $00, $0E, $00, $00, $06, $00, $00, $00, $00, $00  ; rows 12..15
; slot 02/15 of "Magick" row -- wand_orb
magic_wand_orb_pat:
        .byte $00, $00, $00, $00, $10, $00, $00, $01, $00, $00, $3C, $00  ; rows 00..03
        .byte $00, $2E, $01, $20, $26, $00, $00, $22, $00, $40, $1E, $00  ; rows 04..07
        .byte $40, $40, $00, $60, $03, $00, $70, $08, $00, $38, $00, $00  ; rows 08..11
        .byte $1C, $00, $00, $0E, $00, $00, $06, $00, $00, $00, $00, $00  ; rows 12..15
; slot 03/15 of "Magick" row -- wand_skull
magic_wand_skull_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $3E, $00, $00, $7F, $00  ; rows 00..03
        .byte $00, $33, $00, $00, $33, $00, $00, $5E, $00, $00, $79, $00  ; rows 04..07
        .byte $40, $2B, $00, $60, $01, $00, $70, $00, $00, $38, $00, $00  ; rows 08..11
        .byte $1C, $00, $00, $0E, $00, $00, $06, $00, $00, $00, $00, $00  ; rows 12..15
; slot 04/15 of "Magick" row -- orb
magic_orb_pat:
        .byte $00, $00, $00, $00, $00, $00, $60, $0F, $00, $10, $10, $00  ; rows 00..03
        .byte $68, $23, $00, $74, $47, $00, $74, $47, $00, $74, $47, $00  ; rows 04..07
        .byte $64, $4B, $00, $04, $5C, $00, $44, $48, $00, $08, $22, $00  ; rows 08..11
        .byte $10, $10, $00, $60, $0F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 05/15 of "Magick" row -- ankh
magic_ankh_pat:
        .byte $00, $00, $00, $40, $07, $00, $60, $0F, $00, $20, $08, $00  ; rows 00..03
        .byte $60, $0C, $00, $60, $0F, $00, $40, $07, $00, $7C, $7F, $00  ; rows 04..07
        .byte $7C, $7F, $00, $40, $07, $00, $5C, $77, $00, $40, $07, $00  ; rows 08..11
        .byte $40, $07, $00, $00, $00, $00, $40, $07, $00, $00, $00, $00  ; rows 12..15
; slot 06/15 of "Magick" row -- effigy
magic_effigy_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $70, $0D, $00  ; rows 00..03
        .byte $68, $1F, $00, $7C, $3F, $00, $7C, $2F, $00, $30, $1C, $00  ; rows 04..07
        .byte $30, $38, $00, $30, $38, $00, $4C, $1F, $00, $4C, $07, $00  ; rows 08..11
        .byte $78, $01, $00, $38, $01, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 07/15 of "Magick" row -- scroll
magic_scroll_pat:
        .byte $00, $00, $00, $60, $7F, $00, $10, $7F, $01, $50, $7F, $01  ; rows 00..03
        .byte $10, $00, $00, $70, $3F, $00, $10, $20, $00, $70, $3F, $00  ; rows 04..07
        .byte $30, $30, $00, $70, $3F, $00, $10, $20, $00, $70, $3F, $00  ; rows 08..11
        .byte $36, $30, $00, $72, $3F, $00, $7C, $1F, $00, $00, $00, $00  ; rows 12..15
; slot 08/15 of "Magick" row -- scroll_open
magic_scroll_open_pat:
        .byte $00, $00, $00, $74, $5F, $00, $6E, $3F, $01, $68, $3F, $01  ; rows 00..03
        .byte $04, $00, $00, $00, $00, $00, $08, $10, $00, $78, $1F, $00  ; rows 04..07
        .byte $08, $10, $00, $78, $1F, $00, $00, $00, $00, $74, $5F, $00  ; rows 08..11
        .byte $6E, $3F, $01, $68, $3F, $01, $04, $00, $00, $00, $00, $00  ; rows 12..15
; slot 09/15 of "Magick" row -- runestone
magic_runestone_pat:
        .byte $00, $00, $00, $00, $18, $00, $00, $1E, $00, $40, $1F, $00  ; rows 00..03
        .byte $70, $19, $00, $38, $18, $00, $18, $1C, $00, $18, $5F, $00  ; rows 04..07
        .byte $78, $5F, $00, $78, $47, $00, $78, $41, $00, $38, $40, $00  ; rows 08..11
        .byte $68, $5F, $00, $68, $5F, $00, $70, $7F, $00, $00, $00, $00  ; rows 12..15
; slot 10/15 of "Magick" row -- book
magic_book_pat:
        .byte $00, $00, $00, $7E, $7F, $01, $02, $00, $01, $7A, $7F, $01  ; rows 00..03
        .byte $7A, $7F, $01, $7A, $7F, $01, $7A, $7F, $01, $7A, $7F, $01  ; rows 04..07
        .byte $7E, $7F, $01, $00, $00, $00, $7E, $7F, $01, $00, $00, $00  ; rows 08..11
        .byte $64, $4C, $00, $7C, $7F, $00, $7E, $7F, $01, $00, $00, $00  ; rows 12..15
; slot 11/15 of "Magick" row -- mirror
magic_mirror_pat:
        .byte $00, $00, $00, $60, $0F, $00, $18, $30, $00, $04, $40, $00  ; rows 00..03
        .byte $62, $04, $01, $02, $10, $01, $02, $03, $01, $04, $40, $00  ; rows 04..07
        .byte $1A, $30, $01, $62, $0F, $01, $06, $40, $01, $1E, $70, $01  ; rows 08..11
        .byte $7E, $7F, $01, $7C, $7F, $00, $72, $1F, $01, $00, $03, $00  ; rows 12..15
; slot 12/15 of "Magick" row -- vortex
magic_vortex_pat:
        .byte $00, $00, $00, $02, $02, $01, $04, $40, $00, $40, $0F, $00  ; rows 00..03
        .byte $20, $10, $00, $10, $20, $00, $08, $0F, $00, $4A, $10, $00  ; rows 04..07
        .byte $48, $24, $01, $08, $23, $00, $08, $20, $00, $10, $10, $00  ; rows 08..11
        .byte $60, $0F, $00, $04, $40, $00, $02, $01, $01, $00, $00, $00  ; rows 12..15
; slot 13/15 of "Magick" row -- portal
magic_portal_pat:
        .byte $00, $00, $00, $00, $20, $00, $08, $20, $00, $7E, $7F, $00  ; rows 00..03
        .byte $08, $20, $00, $28, $28, $00, $48, $24, $00, $08, $22, $00  ; rows 04..07
        .byte $08, $21, $00, $48, $24, $00, $28, $28, $00, $08, $20, $00  ; rows 08..11
        .byte $7C, $7F, $01, $08, $20, $00, $08, $00, $00, $00, $00, $00  ; rows 12..15
; slot 14/15 of "Magick" row -- hand
magic_hand_pat:
        .byte $00, $00, $00, $02, $00, $01, $04, $45, $00, $20, $05, $00  ; rows 00..03
        .byte $20, $05, $00, $20, $15, $00, $20, $15, $00, $26, $55, $01  ; rows 04..07
        .byte $60, $1F, $00, $64, $18, $00, $68, $1A, $00, $70, $18, $00  ; rows 08..11
        .byte $60, $1F, $00, $44, $4F, $00, $02, $00, $01, $00, $00, $00  ; rows 12..15
; slot 15/15 of "Magick" row -- sun
magic_sun_pat:
        .byte $00, $00, $00, $40, $07, $00, $30, $1C, $00, $08, $22, $00  ; rows 00..03
        .byte $04, $41, $00, $04, $41, $00, $02, $41, $01, $02, $22, $01  ; rows 04..07
        .byte $02, $1C, $01, $62, $00, $01, $64, $40, $00, $04, $40, $00  ; rows 08..11
        .byte $08, $20, $00, $30, $18, $00, $40, $07, $00, $00, $00, $00  ; rows 12..15
