# A1-IO RTC Clock
PROJECT  := RtcClock
LOAD_CFG := ../../../cc65/apple1_4k.cfg
OUT_DIR  := ../../../../software/a1io_rtc
LIB      := -I ../../../lib/apple1 -I ../../../lib/a1io
EMIT_TXT := 1            # regenerate the canonical Wozmon-hex RtcClock.txt

include ../../../cc65/Makefile.common
