# HGR Orbital Pool
PROJECT  := HGR_OrbitalPool
LOAD_CFG := ../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../software/Graphic HGR
LIB      := -I ../../lib/apple1
EMIT_TXT := 1

include ../../cc65/Makefile.common
