# CodeTank upper-bank Tetris loader (128 B at $4000)
PROJECT  := tetris_loader
LOAD_CFG := apple1_tetris_loader.cfg
OUT_DIR  := ../../../software/tms9918
LIB      := -I ../../lib/apple1

include ../../cc65/Makefile.common
