# HGR Mandelbrot
PROJECT  := HGR_Mandelbrot
LOAD_CFG := ../../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../../software/Graphic HGR
LIB      := -I ../../../lib/apple1 -I ../../../lib/gen2 -I ../../../lib/m6502
EMIT_TXT := 1

include ../../../cc65/Makefile.common
