# CodeTank lower-bank menu (256 B at $4000)
PROJECT  := codetank_menu
LOAD_CFG := apple1_codetank_menu.cfg
OUT_DIR  := ../../../software/Graphic TMS9918
LIB      := -I ../../lib/apple1

include ../../cc65/Makefile.common
