# HGR BB Font Show (CP437 font sheet)
PROJECT  := HGR_BBFontShow
LOAD_CFG := ../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../software/Graphic HGR
LIB      := -I ../../lib/apple1 -I ../../lib/hgr -I ../../lib/m6502
EMIT_TXT := 1

include ../../cc65/Makefile.common
