# GT-6144 Hello
PROJECT  := GT1_Hello
LOAD_CFG := gt6144.cfg
OUT_DIR  := ../../../../software/Graphic gt-6144
LIB      := -I ../../../lib/apple1 -I ../../../lib/gt6144
EMIT_TXT := 1            # regenerate the canonical Wozmon-hex GT1_Hello.txt

include ../../../cc65/Makefile.common
