; ============================================================================
; chess_hgr_masks.asm  --  6 silhouette masks (16x16) for HGR chess
; Generated by tools/build_chess_hgr_masks.py from pic/chess_pieces_16x16.png.
; DO NOT EDIT BY HAND -- rerun the generator instead.
; ----------------------------------------------------------------------------
; One silhouette mask per piece type. 16 rows x 3 bytes; bit 0 = leftmost
; pixel, 7 px/byte (bits 0..6), bit 7 clear. 1 = piece pixel. The 16-px
; silhouette is shifted right 2 px to centre it in a 21-px (3-byte) square.
; The renderer paints these pixels BLACK (clear) or ORANGE (stamp) over the
; already-drawn square colour, so ONE mask serves both sides.
; ============================================================================
; Emitted into CODE so the sketch can `.include` this file directly into a
; single self-contained assembly unit (no external link step).
.export chess_king_mask, chess_queen_mask, chess_bishop_mask, chess_knight_mask, chess_rook_mask, chess_pawn_mask

.segment "CODE"

; king
chess_king_mask:
        .byte $00, $1E, $00   ; row 00
        .byte $00, $3F, $00   ; row 01
        .byte $00, $3F, $00   ; row 02
        .byte $60, $7F, $01   ; row 03
        .byte $70, $7F, $03   ; row 04
        .byte $78, $7F, $07   ; row 05
        .byte $7C, $7F, $0F   ; row 06
        .byte $7C, $7F, $0F   ; row 07
        .byte $7C, $7F, $0F   ; row 08
        .byte $7C, $7F, $0F   ; row 09
        .byte $78, $7F, $07   ; row 10
        .byte $70, $7F, $03   ; row 11
        .byte $70, $7F, $03   ; row 12
        .byte $70, $7F, $03   ; row 13
        .byte $70, $7F, $03   ; row 14
        .byte $60, $7F, $01   ; row 15

; queen
chess_queen_mask:
        .byte $00, $0C, $00   ; row 00
        .byte $00, $1E, $00   ; row 01
        .byte $04, $1E, $08   ; row 02
        .byte $0C, $3F, $0C   ; row 03
        .byte $3C, $3F, $0F   ; row 04
        .byte $7C, $7F, $0F   ; row 05
        .byte $7C, $7F, $0F   ; row 06
        .byte $78, $7F, $07   ; row 07
        .byte $78, $7F, $07   ; row 08
        .byte $78, $7F, $07   ; row 09
        .byte $70, $7F, $03   ; row 10
        .byte $70, $7F, $03   ; row 11
        .byte $78, $7F, $07   ; row 12
        .byte $78, $7F, $07   ; row 13
        .byte $78, $7F, $07   ; row 14
        .byte $60, $7F, $01   ; row 15

; bishop
chess_bishop_mask:
        .byte $00, $0C, $00   ; row 00
        .byte $00, $1E, $00   ; row 01
        .byte $00, $0C, $00   ; row 02
        .byte $00, $1E, $00   ; row 03
        .byte $00, $3F, $00   ; row 04
        .byte $40, $7F, $00   ; row 05
        .byte $60, $7F, $01   ; row 06
        .byte $60, $7F, $01   ; row 07
        .byte $60, $7F, $01   ; row 08
        .byte $40, $7F, $01   ; row 09
        .byte $40, $7F, $00   ; row 10
        .byte $40, $7F, $00   ; row 11
        .byte $00, $3F, $00   ; row 12
        .byte $40, $7F, $00   ; row 13
        .byte $60, $7F, $01   ; row 14
        .byte $60, $7F, $01   ; row 15

; knight
chess_knight_mask:
        .byte $00, $1B, $00   ; row 00
        .byte $40, $3F, $00   ; row 01
        .byte $60, $7F, $00   ; row 02
        .byte $70, $7F, $01   ; row 03
        .byte $78, $7F, $01   ; row 04
        .byte $7C, $7F, $03   ; row 05
        .byte $7C, $7F, $03   ; row 06
        .byte $78, $7F, $03   ; row 07
        .byte $30, $7E, $03   ; row 08
        .byte $00, $7F, $01   ; row 09
        .byte $40, $7F, $01   ; row 10
        .byte $60, $7F, $01   ; row 11
        .byte $60, $7F, $01   ; row 12
        .byte $70, $7F, $03   ; row 13
        .byte $70, $7F, $03   ; row 14
        .byte $70, $7F, $03   ; row 15

; rook
chess_rook_mask:
        .byte $70, $6D, $03   ; row 00
        .byte $70, $7F, $03   ; row 01
        .byte $70, $7F, $03   ; row 02
        .byte $70, $7F, $03   ; row 03
        .byte $70, $7F, $03   ; row 04
        .byte $60, $7F, $01   ; row 05
        .byte $40, $7F, $00   ; row 06
        .byte $40, $7F, $00   ; row 07
        .byte $40, $7F, $00   ; row 08
        .byte $40, $7F, $00   ; row 09
        .byte $40, $7F, $00   ; row 10
        .byte $60, $7F, $01   ; row 11
        .byte $60, $7F, $01   ; row 12
        .byte $70, $7F, $03   ; row 13
        .byte $70, $7F, $03   ; row 14
        .byte $70, $7F, $03   ; row 15

; pawn
chess_pawn_mask:
        .byte $00, $00, $00   ; row 00
        .byte $00, $0C, $00   ; row 01
        .byte $00, $1E, $00   ; row 02
        .byte $00, $3F, $00   ; row 03
        .byte $00, $3F, $00   ; row 04
        .byte $00, $1E, $00   ; row 05
        .byte $00, $3F, $00   ; row 06
        .byte $00, $3F, $00   ; row 07
        .byte $00, $3F, $00   ; row 08
        .byte $40, $7F, $00   ; row 09
        .byte $60, $7F, $01   ; row 10
        .byte $60, $7F, $01   ; row 11
        .byte $60, $7F, $01   ; row 12
        .byte $60, $7F, $01   ; row 13
        .byte $60, $7F, $01   ; row 14
        .byte $00, $00, $00   ; row 15

