; ============================================================================
; sprites_emotes_hgr.asm  --  14 sprites in GEN2 HGR format
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "emotes" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_emotes.asm. Do not edit by hand —
; rerun the tool to refresh after changing the TMS source.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte; bit 7 stays
; clear (NTSC group selector). 16-px sprite occupies cols 0..6
; in byte 0, cols 7..13 in byte 1, cols 14..15 in bits 0..1 of
; byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export normal_pat, happy_pat, super_pat, sad_pat, upset_pat
.export angry_pat, grumpy_pat, perv_pat, sick_pat, sleep_pat
.export pirate_pat, shades_pat, bird1_pat, bird2_pat
.export emotes_hgr_data

; Constants like EMOTES_HGR_COUNT live in the sister
; sprites_emotes_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

emotes_hgr_data:
normal_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $46, $0F, $01, $6E, $5F, $01  ; rows 04..07
        .byte $6E, $5F, $01, $7E, $7F, $01, $3E, $60, $01, $7E, $7F, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
happy_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $46, $0F, $01, $6E, $5F, $01  ; rows 04..07
        .byte $6E, $5F, $01, $7E, $7F, $01, $3E, $6F, $01, $7E, $70, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
super_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $6E, $3F, $01, $6E, $3F, $01  ; rows 04..07
        .byte $6E, $3F, $01, $7E, $7F, $01, $3E, $60, $01, $3E, $60, $01  ; rows 08..11
        .byte $7C, $70, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
sad_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $4E, $4F, $01, $66, $1F, $01  ; rows 04..07
        .byte $6E, $5F, $01, $7E, $7F, $01, $7E, $70, $01, $3E, $6F, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
upset_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $66, $1F, $01, $4E, $4F, $01  ; rows 04..07
        .byte $66, $1F, $01, $7E, $7F, $01, $7E, $70, $01, $3E, $60, $01  ; rows 08..11
        .byte $3C, $60, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
angry_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $66, $1F, $01, $4E, $4F, $01  ; rows 04..07
        .byte $6E, $5F, $01, $7E, $7F, $01, $7E, $70, $01, $3E, $6F, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
grumpy_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $66, $1F, $01, $4E, $4F, $01  ; rows 04..07
        .byte $6E, $5F, $01, $7E, $7F, $01, $7E, $60, $01, $3E, $60, $01  ; rows 08..11
        .byte $3C, $70, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
perv_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $7E, $7F, $01, $46, $0F, $01  ; rows 04..07
        .byte $76, $6F, $01, $7E, $7F, $01, $7E, $7E, $01, $7E, $79, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
sick_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $7E, $7F, $01, $5E, $6F, $01  ; rows 04..07
        .byte $7E, $7F, $01, $7E, $76, $01, $7E, $70, $01, $7E, $76, $01  ; rows 08..11
        .byte $3C, $6F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
sleep_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $7E, $7F, $01, $5E, $3F, $01  ; rows 04..07
        .byte $66, $4F, $01, $7E, $7F, $01, $7E, $79, $01, $7E, $7F, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
pirate_pat:
        .byte $00, $00, $00, $00, $00, $00, $70, $3F, $00, $4C, $7F, $00  ; rows 00..03
        .byte $3E, $7E, $01, $7E, $79, $00, $66, $07, $01, $4E, $07, $01  ; rows 04..07
        .byte $6E, $0F, $01, $7E, $7F, $01, $3E, $60, $01, $7E, $7F, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
shades_pat:
        .byte $00, $00, $00, $00, $00, $00, $78, $3F, $00, $7C, $7F, $00  ; rows 00..03
        .byte $7E, $7F, $01, $7E, $7F, $01, $00, $00, $00, $76, $76, $00  ; rows 04..07
        .byte $76, $76, $00, $0E, $0F, $01, $7E, $79, $01, $7E, $7F, $01  ; rows 08..11
        .byte $7C, $7F, $00, $78, $3F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
bird1_pat:
        .byte $00, $00, $00, $01, $00, $02, $03, $00, $03, $06, $40, $01  ; rows 00..03
        .byte $1C, $70, $00, $70, $1F, $00, $40, $04, $00, $40, $07, $00  ; rows 04..07
        .byte $40, $07, $00, $40, $04, $00, $00, $00, $00, $00, $00, $00  ; rows 08..11
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
bird2_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $00, $00, $00, $40, $04, $00, $40, $07, $00, $40, $07, $00  ; rows 04..07
        .byte $40, $04, $00, $70, $1F, $00, $1C, $70, $00, $06, $40, $01  ; rows 08..11
        .byte $03, $00, $03, $01, $00, $02, $00, $00, $00, $00, $00, $00  ; rows 12..15
