; ============================================================================
; sprites_trollkind_hgr.asm  --  4 sprites, GEN2 HGR x1 mono master
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "Trollkind" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_trollkind.asm. Do not edit by hand --
; rerun the tool to refresh after changing the TMS source.
;
; REGIME: x1 mono. On HGR the colour is a pure NTSC ARTIFACT (Woz's
; trick), NOT a chosen colour. This is the compact 48-byte master; for
; a CHOSEN colour, double it to x2 in the POM1 HGR Sprite editor (per-
; project, 4x the bytes) or at runtime via gen2_hgr_inflate_x2.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte. Bit 7 = palette
; GROUP (0 = violet/green, 1 = blue/orange), emitted as group 0 here;
; the editor can flip it per sprite. 16-px sprite: cols 0..6 in byte 0,
; cols 7..13 in byte 1, cols 14..15 in bits 0..1 of byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export troll_grunt_pat, troll_warrior_pat, troll_chief_pat, troll_brute_pat
.export trollkind_hgr_data

; Constants like TROLLKIND_HGR_COUNT live in the sister
; sprites_trollkind_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

trollkind_hgr_data:
; slot 01/4 of "Trollkind" row -- grunt
troll_grunt_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $00, $00, $00, $6E, $6F, $01, $3C, $7B, $00, $70, $1F, $00  ; rows 04..07
        .byte $60, $0F, $00, $10, $10, $00, $78, $3F, $00, $6C, $6F, $00  ; rows 08..11
        .byte $64, $4F, $00, $6C, $6C, $00, $4C, $64, $00, $40, $04, $00  ; rows 12..15
; slot 02/4 of "Trollkind" row -- warrior
troll_warrior_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $6C, $6F, $00  ; rows 00..03
        .byte $78, $3F, $00, $50, $17, $00, $78, $3C, $00, $3C, $78, $00  ; rows 04..07
        .byte $3E, $7A, $01, $6E, $6F, $01, $1E, $70, $01, $76, $5F, $01  ; rows 08..11
        .byte $72, $1F, $01, $76, $5F, $01, $36, $58, $01, $20, $08, $00  ; rows 12..15
; slot 03/4 of "Trollkind" row -- chief
troll_chief_pat:
        .byte $00, $00, $00, $00, $01, $00, $00, $03, $00, $60, $0F, $00  ; rows 00..03
        .byte $70, $1F, $00, $30, $18, $00, $78, $3C, $00, $7C, $7F, $00  ; rows 04..07
        .byte $3E, $78, $01, $6E, $6F, $01, $1E, $70, $01, $76, $5F, $01  ; rows 08..11
        .byte $72, $1F, $01, $76, $5F, $01, $36, $58, $01, $20, $08, $00  ; rows 12..15
; slot 04/4 of "Trollkind" row -- brute
troll_brute_pat:
        .byte $00, $00, $00, $10, $10, $00, $48, $27, $00, $78, $3F, $00  ; rows 00..03
        .byte $70, $1F, $00, $20, $0B, $00, $78, $3F, $00, $1C, $74, $00  ; rows 04..07
        .byte $5E, $71, $01, $6E, $6F, $01, $1E, $70, $01, $76, $5F, $01  ; rows 08..11
        .byte $72, $1F, $01, $76, $5F, $01, $36, $58, $01, $20, $08, $00  ; rows 12..15
