; ============================================================================
; sprites_traps_devices_hgr.asm  --  12 sprites, GEN2 HGR x1 mono master
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "Traps & Devices" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_traps_devices.asm. Do not edit by hand --
; rerun the tool to refresh after changing the TMS source.
;
; REGIME: x1 mono. On HGR the colour is a pure NTSC ARTIFACT (Woz's
; trick), NOT a chosen colour. This is the compact 48-byte master; for
; a CHOSEN colour, double it to x2 in the POM1 HGR Sprite editor (per-
; project, 4x the bytes) or at runtime via gen2_hgr_inflate_x2.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte. Bit 7 = palette
; GROUP (0 = violet/green, 1 = blue/orange), emitted as group 0 here;
; the editor can flip it per sprite. 16-px sprite: cols 0..6 in byte 0,
; cols 7..13 in byte 1, cols 14..15 in bits 0..1 of byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export trap_grate_pat, trap_web_pat, trap_beartrap_ready_pat, trap_beartrap_used_pat, trap_trap_ready_pat
.export trap_trap_used_pat, trap_trapdoor_ready_pat, trap_trapdoor_used_pat, trap_button_ready_pat, trap_button_used_pat
.export trap_switch_left_pat, trap_switch_right_pat
.export traps_devices_hgr_data

; Constants like TRAPS_DEVICES_HGR_COUNT live in the sister
; sprites_traps_devices_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

traps_devices_hgr_data:
; slot 01/12 of "Traps & Devices" row -- grate  (was: net)
trap_grate_pat:
        .byte $00, $00, $00, $40, $04, $00, $48, $24, $00, $7C, $7F, $00  ; rows 00..03
        .byte $48, $24, $00, $48, $24, $00, $6E, $7F, $01, $48, $24, $00  ; rows 04..07
        .byte $48, $20, $00, $7E, $71, $01, $48, $20, $00, $48, $24, $00  ; rows 08..11
        .byte $7C, $7F, $00, $48, $24, $00, $40, $04, $00, $00, $00, $00  ; rows 12..15
; slot 02/12 of "Traps & Devices" row -- web
trap_web_pat:
        .byte $00, $00, $00, $08, $08, $00, $50, $0F, $00, $28, $38, $01  ; rows 00..03
        .byte $48, $46, $00, $2E, $2D, $00, $34, $52, $00, $54, $4B, $00  ; rows 04..07
        .byte $24, $57, $00, $14, $59, $00, $68, $6A, $01, $44, $25, $00  ; rows 08..11
        .byte $3A, $28, $00, $60, $17, $00, $20, $20, $00, $00, $00, $00  ; rows 12..15
; slot 03/12 of "Traps & Devices" row -- beartrap_ready  (was: spikes)
trap_beartrap_ready_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $00, $00, $00, $00, $00, $00, $60, $0F, $00, $00, $00, $00  ; rows 04..07
        .byte $2A, $2B, $01, $7E, $7C, $01, $00, $00, $00, $00, $00, $00  ; rows 08..11
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 04/12 of "Traps & Devices" row -- beartrap_used  (was: caltrops)
trap_beartrap_used_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $40, $06, $00, $40, $05, $00, $40, $06, $00, $40, $05, $00  ; rows 04..07
        .byte $40, $06, $00, $40, $05, $00, $00, $00, $00, $00, $03, $00  ; rows 08..11
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 05/12 of "Traps & Devices" row -- trap_ready  (was: dart)
trap_trap_ready_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $40, $10, $00, $60, $18, $00, $60, $18, $00, $00, $00, $00  ; rows 04..07
        .byte $00, $00, $00, $20, $08, $00, $30, $0C, $00, $30, $0C, $00  ; rows 08..11
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 06/12 of "Traps & Devices" row -- trap_used  (was: pit)
trap_trap_used_pat:
        .byte $00, $00, $00, $7C, $7F, $00, $06, $40, $01, $02, $00, $01  ; rows 00..03
        .byte $42, $10, $01, $62, $18, $01, $62, $18, $01, $02, $00, $01  ; rows 04..07
        .byte $02, $00, $01, $22, $08, $01, $32, $0C, $01, $32, $0C, $01  ; rows 08..11
        .byte $02, $00, $01, $06, $40, $01, $7C, $7F, $00, $00, $00, $00  ; rows 12..15
; slot 07/12 of "Traps & Devices" row -- trapdoor_ready  (was: grate)
trap_trapdoor_ready_pat:
        .byte $00, $00, $00, $7C, $7F, $00, $06, $40, $01, $72, $1F, $01  ; rows 00..03
        .byte $4A, $24, $01, $4A, $24, $01, $7A, $3F, $01, $4A, $24, $01  ; rows 04..07
        .byte $4A, $24, $01, $7A, $3F, $01, $4A, $24, $01, $4A, $24, $01  ; rows 08..11
        .byte $72, $1F, $01, $06, $40, $01, $7C, $7F, $00, $00, $00, $00  ; rows 12..15
; slot 08/12 of "Traps & Devices" row -- trapdoor_used  (was: chest_open)
trap_trapdoor_used_pat:
        .byte $00, $00, $00, $7C, $7F, $00, $06, $40, $01, $02, $00, $01  ; rows 00..03
        .byte $02, $00, $01, $02, $00, $01, $02, $00, $01, $02, $00, $01  ; rows 04..07
        .byte $02, $00, $01, $02, $00, $01, $02, $00, $01, $02, $00, $01  ; rows 08..11
        .byte $72, $1F, $01, $06, $40, $01, $7C, $7F, $00, $00, $00, $00  ; rows 12..15
; slot 09/12 of "Traps & Devices" row -- button_ready  (was: chest)
trap_button_ready_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $78, $3F, $00  ; rows 00..03
        .byte $08, $20, $00, $68, $2F, $00, $68, $2F, $00, $68, $2C, $00  ; rows 04..07
        .byte $68, $2E, $00, $68, $2F, $00, $68, $2F, $00, $08, $20, $00  ; rows 08..11
        .byte $78, $3F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 10/12 of "Traps & Devices" row -- button_used  (was: button)
trap_button_used_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $78, $3F, $00  ; rows 00..03
        .byte $08, $20, $00, $08, $20, $00, $48, $2F, $00, $48, $2F, $00  ; rows 04..07
        .byte $48, $29, $00, $48, $2D, $00, $48, $2F, $00, $08, $20, $00  ; rows 08..11
        .byte $78, $3F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 11/12 of "Traps & Devices" row -- switch_left  (was: lever_down)
trap_switch_left_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $06, $00, $00  ; rows 00..03
        .byte $06, $00, $00, $08, $00, $00, $10, $00, $00, $20, $00, $00  ; rows 04..07
        .byte $58, $3E, $00, $0C, $61, $00, $7C, $7F, $00, $7C, $7F, $00  ; rows 08..11
        .byte $7C, $7F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 12/12 of "Traps & Devices" row -- switch_right  (was: lever_up)
trap_switch_right_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $40, $01  ; rows 00..03
        .byte $00, $40, $01, $00, $20, $00, $00, $10, $00, $00, $08, $00  ; rows 04..07
        .byte $78, $35, $00, $0C, $62, $00, $7C, $7F, $00, $7C, $7F, $00  ; rows 08..11
        .byte $7C, $7F, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
