; ============================================================================
; sprites_chess_hgr.asm  --  6 sprites, GEN2 HGR x1 mono master
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "chess" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_chess.asm. Do not edit by hand --
; rerun the tool to refresh after changing the TMS source.
;
; REGIME: x1 mono. On HGR the colour is a pure NTSC ARTIFACT (Woz's
; trick), NOT a chosen colour. This is the compact 48-byte master; for
; a CHOSEN colour, double it to x2 in the POM1 HGR Sprite editor (per-
; project, 4x the bytes) or at runtime via gen2_hgr_inflate_x2.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte. Bit 7 = palette
; GROUP (0 = violet/green, 1 = blue/orange), emitted as group 0 here;
; the editor can flip it per sprite. 16-px sprite: cols 0..6 in byte 0,
; cols 7..13 in byte 1, cols 14..15 in bits 0..1 of byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export chess_king_pat, chess_queen_pat, chess_bishop_pat, chess_knight_pat, chess_rook_pat
.export chess_pawn_pat
.export chess_hgr_data

; Constants like CHESS_HGR_COUNT live in the sister
; sprites_chess_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

chess_hgr_data:
chess_king_pat:
        .byte $40, $07, $00, $60, $0C, $00, $20, $0B, $00, $38, $3B, $00  ; rows 00..03
        .byte $44, $44, $00, $3A, $3B, $01, $7D, $7C, $02, $7D, $7C, $02  ; rows 04..07
        .byte $7D, $7C, $02, $7D, $7F, $02, $0A, $20, $01, $74, $5F, $00  ; rows 08..11
        .byte $04, $40, $00, $74, $5F, $00, $0C, $60, $00, $78, $3F, $00  ; rows 12..15
chess_queen_pat:
        .byte $00, $03, $00, $40, $04, $00, $41, $04, $02, $23, $0B, $03  ; rows 00..03
        .byte $2D, $6B, $02, $51, $17, $02, $6D, $6F, $02, $7A, $3F, $01  ; rows 04..07
        .byte $7A, $3F, $01, $0A, $20, $01, $74, $5F, $00, $04, $40, $00  ; rows 08..11
        .byte $72, $1F, $01, $7A, $3F, $01, $06, $40, $01, $78, $3F, $00  ; rows 12..15
chess_bishop_pat:
        .byte $00, $03, $00, $40, $04, $00, $00, $03, $00, $40, $04, $00  ; rows 00..03
        .byte $20, $0B, $00, $50, $17, $00, $68, $2B, $00, $68, $2D, $00  ; rows 04..07
        .byte $68, $2F, $00, $50, $27, $00, $10, $10, $00, $50, $17, $00  ; rows 08..11
        .byte $20, $0B, $00, $50, $17, $00, $08, $20, $00, $78, $3F, $00  ; rows 12..15
chess_knight_pat:
        .byte $40, $04, $00, $50, $0D, $00, $68, $17, $00, $54, $2F, $00  ; rows 00..03
        .byte $6A, $2D, $00, $3D, $6E, $00, $4D, $5E, $00, $72, $5E, $00  ; rows 04..07
        .byte $4C, $5E, $00, $20, $2F, $00, $50, $2F, $00, $68, $2F, $00  ; rows 08..11
        .byte $68, $2F, $00, $7C, $7F, $00, $04, $40, $00, $7C, $7F, $00  ; rows 12..15
chess_rook_pat:
        .byte $3C, $7B, $00, $44, $44, $00, $14, $53, $00, $74, $5F, $00  ; rows 00..03
        .byte $04, $40, $00, $68, $2F, $00, $50, $17, $00, $50, $17, $00  ; rows 04..07
        .byte $50, $17, $00, $50, $17, $00, $50, $17, $00, $68, $2F, $00  ; rows 08..11
        .byte $08, $20, $00, $74, $5F, $00, $04, $40, $00, $7C, $7F, $00  ; rows 12..15
chess_pawn_pat:
        .byte $00, $00, $00, $00, $03, $00, $40, $04, $00, $20, $0B, $00  ; rows 00..03
        .byte $20, $0B, $00, $40, $04, $00, $20, $0B, $00, $20, $0B, $00  ; rows 04..07
        .byte $20, $0B, $00, $50, $17, $00, $68, $2F, $00, $08, $20, $00  ; rows 08..11
        .byte $78, $3F, $00, $08, $20, $00, $78, $3F, $00, $00, $00, $00  ; rows 12..15
