; ============================================================================
; sprites_music_hgr.asm  --  6 sprites, GEN2 HGR x1 mono master
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "Music" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_music.asm. Do not edit by hand --
; rerun the tool to refresh after changing the TMS source.
;
; REGIME: x1 mono. On HGR the colour is a pure NTSC ARTIFACT (Woz's
; trick), NOT a chosen colour. This is the compact 48-byte master; for
; a CHOSEN colour, double it to x2 in the POM1 HGR Sprite editor (per-
; project, 4x the bytes) or at runtime via gen2_hgr_inflate_x2.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte. Bit 7 = palette
; GROUP (0 = violet/green, 1 = blue/orange), emitted as group 0 here;
; the editor can flip it per sprite. 16-px sprite: cols 0..6 in byte 0,
; cols 7..13 in byte 1, cols 14..15 in bits 0..1 of byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export music_lute_pat, music_harp_pat, music_panpipe_pat, music_horn_pat, music_flute_pat
.export music_singer_pat
.export music_hgr_data

; Constants like MUSIC_HGR_COUNT live in the sister
; sprites_music_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

music_hgr_data:
; slot 01/6 of "Music" row -- lute
music_lute_pat:
        .byte $00, $00, $00, $00, $10, $00, $00, $68, $01, $00, $70, $01  ; rows 00..03
        .byte $00, $38, $00, $00, $1C, $00, $78, $0F, $00, $7C, $07, $00  ; rows 04..07
        .byte $7E, $03, $00, $4E, $05, $00, $0A, $06, $00, $16, $07, $00  ; rows 08..11
        .byte $6E, $07, $00, $5C, $03, $00, $78, $01, $00, $00, $00, $00  ; rows 12..15
; slot 02/6 of "Music" row -- harp
music_harp_pat:
        .byte $00, $00, $00, $7C, $00, $00, $7C, $01, $00, $00, $03, $00  ; rows 00..03
        .byte $48, $06, $00, $48, $3C, $00, $48, $42, $00, $48, $4A, $00  ; rows 04..07
        .byte $48, $6A, $00, $48, $3A, $00, $48, $3A, $00, $48, $1E, $00  ; rows 08..11
        .byte $48, $1E, $00, $48, $0F, $00, $7C, $0F, $00, $00, $00, $00  ; rows 12..15
; slot 03/6 of "Music" row -- panpipe
music_panpipe_pat:
        .byte $00, $00, $00, $00, $00, $00, $30, $15, $00, $70, $3F, $00  ; rows 00..03
        .byte $00, $00, $00, $30, $15, $00, $30, $05, $00, $30, $05, $00  ; rows 04..07
        .byte $30, $01, $00, $30, $01, $00, $30, $01, $00, $30, $00, $00  ; rows 08..11
        .byte $30, $00, $00, $30, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 04/6 of "Music" row -- horn
music_horn_pat:
        .byte $00, $00, $00, $00, $40, $01, $00, $60, $01, $00, $40, $00  ; rows 00..03
        .byte $00, $0E, $00, $40, $1F, $00, $78, $1F, $00, $44, $1F, $00  ; rows 04..07
        .byte $04, $0F, $00, $24, $0E, $00, $64, $04, $00, $08, $04, $00  ; rows 08..11
        .byte $10, $04, $00, $60, $03, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 05/6 of "Music" row -- flute
music_flute_pat:
        .byte $00, $00, $00, $02, $00, $01, $04, $40, $00, $08, $20, $00  ; rows 00..03
        .byte $10, $10, $00, $66, $4C, $01, $66, $4C, $01, $06, $40, $01  ; rows 04..07
        .byte $36, $5B, $01, $36, $1B, $00, $36, $43, $01, $36, $18, $00  ; rows 08..11
        .byte $06, $03, $00, $30, $00, $00, $06, $00, $00, $00, $00, $00  ; rows 12..15
; slot 06/6 of "Music" row -- singer
music_singer_pat:
        .byte $00, $00, $00, $08, $20, $00, $10, $10, $00, $60, $0F, $00  ; rows 00..03
        .byte $50, $17, $00, $38, $3B, $00, $78, $3F, $00, $70, $1F, $00  ; rows 04..07
        .byte $68, $2F, $00, $18, $30, $00, $78, $3F, $00, $78, $3F, $00  ; rows 08..11
        .byte $70, $1F, $00, $60, $0F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
