; ============================================================================
; sprites_unliving_hgr.asm  --  8 sprites, GEN2 HGR x1 mono master
; ----------------------------------------------------------------------------
; SCROLL-O-SPRITES "The Unliving" by Quale, May 2013, CC-BY-3.0.
; Auto-generated by tools/build_hgr_sprites.py from
; dev/lib/tms9918/sprites_unliving.asm. Do not edit by hand --
; rerun the tool to refresh after changing the TMS source.
;
; REGIME: x1 mono. On HGR the colour is a pure NTSC ARTIFACT (Woz's
; trick), NOT a chosen colour. This is the compact 48-byte master; for
; a CHOSEN colour, double it to x2 in the POM1 HGR Sprite editor (per-
; project, 4x the bytes) or at runtime via gen2_hgr_inflate_x2.
;
; Layout: each sprite = 16 rows x 3 bytes = 48 B.
; HGR encoding: bit 0 = leftmost pixel within byte. Bit 7 = palette
; GROUP (0 = violet/green, 1 = blue/orange), emitted as group 0 here;
; the editor can flip it per sprite. 16-px sprite: cols 0..6 in byte 0,
; cols 7..13 in byte 1, cols 14..15 in bits 0..1 of byte 2.
;
; Same per-sprite labels as the TMS variant — pick ONE library
; per build (cc65 errors out on duplicate symbols if both are
; linked). The format is implicit in which .o the project
; pulls in.
; ============================================================================
.export undead_zombie_pat, undead_hand_pat, undead_skeleton_pat, undead_diehard_pat, undead_reaper_pat
.export undead_ghost_pat, undead_skull_pat, undead_stalker_pat
.export unliving_hgr_data

; Constants like UNLIVING_HGR_COUNT live in the sister
; sprites_unliving_hgr.inc — projects `.include` it to get the
; sprite count for loop bounds, `CMP #N` immediate forms, etc.
; (cc65 cannot resolve `.import`ed symbols in immediate mode at
; assembly time — the .inc keeps that path clean.)

.segment "CODE"

unliving_hgr_data:
; slot 01/8 of "The Unliving" row -- zombie  (was: undead)
undead_zombie_pat:
        .byte $00, $00, $00, $00, $00, $01, $68, $0F, $00, $70, $1F, $00  ; rows 00..03
        .byte $10, $1F, $00, $10, $17, $00, $70, $1F, $00, $74, $1A, $00  ; rows 04..07
        .byte $30, $18, $00, $20, $08, $01, $1C, $30, $00, $6A, $57, $00  ; rows 08..11
        .byte $62, $4F, $00, $60, $0F, $00, $60, $0C, $00, $40, $14, $00  ; rows 12..15
; slot 02/8 of "The Unliving" row -- hand  (was: skull_small)
undead_hand_pat:
        .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; rows 00..03
        .byte $00, $30, $00, $00, $30, $00, $00, $10, $00, $00, $00, $00  ; rows 04..07
        .byte $00, $3C, $00, $00, $1C, $00, $00, $1E, $00, $58, $3F, $00  ; rows 08..11
        .byte $64, $7F, $00, $20, $66, $00, $10, $42, $00, $10, $02, $00  ; rows 12..15
; slot 03/8 of "The Unliving" row -- crossbones (renamed SKELETON:
undead_skeleton_pat:
        .byte $00, $00, $00, $00, $00, $00, $60, $0F, $00, $70, $1F, $00  ; rows 00..03
        .byte $70, $1F, $00, $10, $13, $00, $10, $13, $00, $70, $1C, $00  ; rows 04..07
        .byte $40, $07, $00, $40, $05, $00, $18, $30, $00, $64, $4F, $00  ; rows 08..11
        .byte $0C, $63, $00, $4C, $67, $00, $20, $08, $00, $20, $08, $00  ; rows 12..15
; slot 04/8 of "The Unliving" row -- diehard  (was: crossbones_big)
undead_diehard_pat:
        .byte $00, $00, $00, $40, $07, $00, $60, $0F, $00, $6C, $6F, $00  ; rows 00..03
        .byte $6E, $6F, $01, $02, $00, $01, $16, $53, $01, $74, $5C, $00  ; rows 04..07
        .byte $40, $07, $00, $5C, $75, $00, $1E, $70, $01, $60, $0F, $00  ; rows 08..11
        .byte $0C, $63, $00, $4C, $67, $00, $20, $08, $00, $20, $08, $00  ; rows 12..15
; slot 05/8 of "The Unliving" row -- reaper  (was: death)
undead_reaper_pat:
        .byte $00, $00, $00, $46, $1F, $00, $6E, $0F, $00, $72, $1F, $00  ; rows 00..03
        .byte $12, $10, $00, $0A, $23, $00, $0A, $23, $00, $6A, $2C, $00  ; rows 04..07
        .byte $4A, $27, $00, $4A, $25, $00, $1E, $10, $00, $7C, $3F, $00  ; rows 08..11
        .byte $7A, $7F, $00, $62, $4F, $00, $62, $1F, $00, $32, $36, $00  ; rows 12..15
; slot 06/8 of "The Unliving" row -- ghost
undead_ghost_pat:
        .byte $00, $00, $00, $60, $0F, $00, $70, $1F, $00, $38, $3F, $00  ; rows 00..03
        .byte $58, $3B, $00, $7A, $37, $01, $3E, $7D, $01, $3E, $78, $01  ; rows 04..07
        .byte $3C, $78, $00, $78, $3A, $00, $78, $3F, $00, $78, $3F, $00  ; rows 08..11
        .byte $70, $3F, $01, $40, $7F, $00, $00, $00, $00, $00, $00, $00  ; rows 12..15
; slot 07/8 of "The Unliving" row -- skull  (was: wraith)
undead_skull_pat:
        .byte $00, $00, $00, $04, $00, $00, $0E, $00, $00, $64, $1F, $00  ; rows 00..03
        .byte $70, $3F, $00, $38, $70, $00, $18, $60, $00, $38, $66, $00  ; rows 04..07
        .byte $38, $66, $00, $58, $70, $00, $18, $3E, $00, $70, $1F, $00  ; rows 08..11
        .byte $60, $43, $00, $00, $00, $00, $08, $00, $00, $00, $00, $00  ; rows 12..15
; slot 08/8 of "The Unliving" row -- stalker  (was: shroud)
undead_stalker_pat:
        .byte $00, $00, $00, $40, $1F, $00, $60, $0F, $00, $70, $1F, $00  ; rows 00..03
        .byte $10, $10, $00, $08, $20, $00, $28, $28, $00, $08, $20, $00  ; rows 04..07
        .byte $08, $20, $00, $00, $00, $00, $0C, $30, $00, $6A, $57, $00  ; rows 08..11
        .byte $72, $4F, $00, $70, $0F, $00, $60, $1F, $00, $30, $36, $00  ; rows 12..15
