# A-1-CrazyCycle — Uncle Bernie GEN2 release card beam-raced demo
PROJECT  := A-1-CrazyCycle
LOAD_CFG := ../../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../../software/Graphic HGR
LIB      := -I ../../../lib/apple1 -I ../../../lib/gen2 -I ../../../lib/gen2
EMIT_TXT := 1

include ../../../cc65/Makefile.common
