# HGR Maze (Recursive Backtracker)
PROJECT  := HGR_Maze
LOAD_CFG := ../../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../../software/Graphic HGR
LIB      := -I ../../../lib/apple1 -I ../../../lib/m6502 -I ../../../lib/gen2
EMIT_TXT := 1

include ../../../cc65/Makefile.common
