# CodeTank GAME3 upper-bank menu (256 B at $4000) — Life / Mandel / Plasma.
PROJECT  := codetank_game3_menu
LOAD_CFG := apple1_codetank_game3_menu.cfg
OUT_DIR  := ../../../../software/Graphic TMS9918
LIB      := -I ../../../lib/apple1

include ../../../cc65/Makefile.common
