#!/usr/bin/env python3
"""Generate dev/lib/sid/sid_notes.inc — 96-note SID frequency table.

The SID frequency formula at the Apple-1's 1.022727 MHz CPU clock:
    sid_value = round(freq_hz * 2^24 / CPU_CLOCK_HZ)

Notes are numbered MIDI-style: index 0 = C0 (16.35 Hz), index 95 = B7
(3951 Hz). 12 notes per octave, equal-temperament tuning anchored at
A4 = 440 Hz (index 57).

Tables emitted:
    sid_notes_lo[96] -- low byte of each 16-bit SID frequency value
    sid_notes_hi[96] -- high byte
    NOTE_<NAME><OCTAVE> -- equate per note (NOTE_CS4 = 49, etc.)

Run:
    python3 tools/build_sid_notes.py > dev/lib/sid/sid_notes.inc
"""
import sys

CPU_CLOCK_HZ = 1_022_727
TWO_24 = 1 << 24
NOTE_NAMES = ['C', 'CS', 'D', 'DS', 'E', 'F', 'FS', 'G', 'GS', 'A', 'AS', 'B']


def freq_for_index(n: int) -> float:
    """Return MIDI-style frequency in Hz for note index n (0=C0, 57=A4)."""
    return 440.0 * (2 ** ((n - 57) / 12.0))


def sid_value(freq_hz: float) -> int:
    val = round(freq_hz * TWO_24 / CPU_CLOCK_HZ)
    return min(val, 65535)


def main() -> int:
    notes = [sid_value(freq_for_index(n)) for n in range(96)]
    out = sys.stdout

    out.write(';' + '=' * 76 + '\n')
    out.write('; sid_notes.inc -- 96-note frequency table (C0..B7) for SID at 1.022727 MHz\n')
    out.write(';' + '=' * 76 + '\n')
    out.write('; Generated by tools/build_sid_notes.py — do not edit by hand.\n')
    out.write('; Index 0 = C0 (16.35 Hz), index 95 = B7 (3951 Hz). 12 notes per octave,\n')
    out.write('; standard equal-temperament tuning (A4 = 440 Hz at index 57).\n')
    out.write(';\n')
    out.write('; SID register format: 16-bit frequency value, lo byte at $C800/$C807/$C80E\n')
    out.write('; (per voice), hi byte at +1. Computed as:\n')
    out.write(';   sid_value = round(freq_hz * 2^24 / CPU_CLOCK_HZ)\n')
    out.write('; where CPU_CLOCK_HZ = 1 022 727 (real Apple-1 clock; same in POM1).\n')
    out.write(';' + '=' * 76 + '\n\n')

    for table_name, shift in (('sid_notes_lo', 0), ('sid_notes_hi', 8)):
        out.write(f'{table_name}:\n')
        for octave in range(8):
            row = [f'${(notes[octave * 12 + s] >> shift) & 0xFF:02X}'
                   for s in range(12)]
            out.write(f"        .byte   {', '.join(row)}    ; octave {octave}\n")
        out.write('\n')

    out.write('; --- Note index equates (MIDI-style numbering from C0 = 0) ------------------\n')
    for n in range(96):
        octave = n // 12
        name = NOTE_NAMES[n % 12]
        out.write(f'NOTE_{name}{octave} = {n}\n')

    return 0


if __name__ == '__main__':
    sys.exit(main())
