#!/usr/bin/env python3
"""
Generate dev/lib/tms9918/sprites_chess.asm from pic/chess_pieces_16x16.png.

Source art: a 96x32 one-bit chess set, 6 columns x 2 rows of 16x16 cells:
  row 0 = "filled" pieces, row 1 = the exact colour-inverse ("outline").
Column order (verified visually): king, queen, bishop, knight, rook, pawn.

The two rows share the SAME silhouette (they differ only in which pixels are
ink vs fill), so for a monochrome TMS9918 sprite/pattern we emit ONE pattern
per piece type = the silhouette (any non-transparent pixel -> bit 1). The
side colour (white vs black) is applied at render time via the TMS9918
colour table, so a single pattern serves both colours.

Output format mirrors dev/lib/tms9918/sprites_fauna.asm (native 16x16 TMS
sprite: 16 bytes left half col 0..7, then 16 bytes right half col 8..15;
MSB = leftmost pixel). Dual labels (bare + _-prefixed) for asm and cc65.

Usage:  python3 tools/build_chess_sprites.py
"""
from __future__ import annotations
import argparse
import pathlib
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC  = ROOT / "pic" / "chess_pieces_16x16.png"
OUT  = ROOT / "dev" / "lib" / "tms9918" / "sprites_chess.asm"

# Column order in pic/chess_pieces_16x16.png, verified visually (col0..col5):
NAMES = ["king", "queen", "bishop", "knight", "rook", "pawn"]


def piece_bytes(im: Image.Image, col: int, row: int, style: str) -> list[int]:
    """32 native-TMS bytes for the 16x16 piece at grid (col,row).

    style='outline': ink = the dark drawn pixels (the piece's outline +
        internal detail lines) -> a recognisable line-art piece, the interior
        showing the square colour through.
    style='silhouette': ink = every non-transparent pixel -> a solid blob.
    """
    ox, oy = col * 16, row * 16
    out = []
    for half in (0, 8):                       # left cols 0..7, then right 8..15
        for y in range(16):
            b = 0
            for bit in range(8):
                x = half + bit
                r, g, bl, a = im.getpixel((ox + x, oy + y))
                if a < 128:
                    continue                  # transparent -> off
                if style == "silhouette":
                    b |= 0x80 >> bit          # any opaque pixel -> ink
                else:                          # outline: only the dark pixels
                    if r < 128:
                        b |= 0x80 >> bit
            out.append(b)
    return out


def fmt(bs: list[int]) -> str:
    lines = []
    for i in range(0, 32, 8):
        lines.append("        .byte " + ", ".join(f"${v:02X}" for v in bs[i:i + 8]))
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--style", choices=["outline", "silhouette"],
                    default="outline",
                    help="outline (line-art, default) or silhouette (solid)")
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()
    out_path = pathlib.Path(args.out)
    style = args.style

    im = Image.open(SRC).convert("RGBA")
    exports = ", ".join(f"_chess_{n}_pat" for n in NAMES)
    exports2 = ", ".join(f"chess_{n}_pat" for n in NAMES)
    parts = [
        "; ============================================================================",
        "; sprites_chess.asm  --  6 sprites (16x16, TMS9918 sprite/pattern mode)",
        "; Generated by tools/build_chess_sprites.py from pic/chess_pieces_16x16.png.",
        "; DO NOT EDIT BY HAND -- rerun the generator instead.",
        "; ----------------------------------------------------------------------------",
        f"; One monochrome {style.upper()} pattern per piece type (pawn,knight,bishop,",
        "; rook,queen,king). The side colour (white/black) is set at render time via",
        "; the TMS9918 colour table, so a single pattern serves both colours.",
        f"; Style '{style}': " + ("ink = the drawn outline + internal detail lines"
                                   if style == "outline"
                                   else "ink = the full solid silhouette") + ".",
        ";",
        "; Native TMS9918 16x16 layout: 32 bytes per piece -- first 16 = left half",
        "; (col 0..7), next 16 = right half (col 8..15); MSB = leftmost pixel.",
        "; ============================================================================",
        f".export {exports}",
        f".export {exports2}",
        "",
        ".segment \"CODE\"",
        "",
    ]
    for col, name in enumerate(NAMES):
        bs = piece_bytes(im, col, 0, style)   # row 0 (row 1 is its colour-inverse)
        parts.append(f"; {name} ({style})")
        parts.append(f"chess_{name}_pat:")
        parts.append(f"_chess_{name}_pat:")
        parts.append(fmt(bs))
    out_path.write_text("\n".join(parts) + "\n")
    print(f"wrote {out_path} ({len(NAMES)} pieces, style={style})")


if __name__ == "__main__":
    main()
