#!/usr/bin/env python3
"""
Generate sketchs/gen2/game_chess/chess_hgr_masks.asm from
pic/chess_pieces_16x16.png.

Unlike the artifact-coloured HGR *sprite* library (sprites_chess_hgr.asm, a
line-art outline whose colour is a pure NTSC artifact), the HGR chess board
draws each piece OVER a coloured square (white / blue) and paints it either
BLACK (clear the piece pixels) or ORANGE (stamp the orange artifact pattern
into the piece pixels). Both operations need a SILHOUETTE MASK: one bit per
pixel, 1 = "this pixel belongs to the piece".

Output: 6 masks (king,queen,bishop,knight,rook,pawn), 16 rows x 3 bytes each.
  HGR byte layout, bit 0 = leftmost pixel, 7 pixels per byte (bits 0..6);
  bit 7 stays clear (it is the NTSC palette-group selector, not a pixel, and
  the renderer never wants the mask to touch it).
The 16-px-wide silhouette is shifted right by SHIFT px so it sits roughly
centred inside a 21-px (3-byte) board square.

Usage:  python3 tools/build_chess_hgr_masks.py
"""
from __future__ import annotations
import pathlib
from PIL import Image

ROOT  = pathlib.Path(__file__).resolve().parents[1]
SRC   = ROOT / "pic" / "chess_pieces_16x16.png"
OUT   = ROOT / "dev" / "lib" / "gen2" / "sprites" / "chess_hgr_masks.asm"

# Column order in pic/chess_pieces_16x16.png (verified visually).
NAMES = ["king", "queen", "bishop", "knight", "rook", "pawn"]
SHIFT = 2          # px to shift right so the 16-px piece centres in 21-px square


def mask_bytes(im: Image.Image, col: int) -> list[int]:
    """16 rows x 3 HGR bytes: silhouette (any opaque pixel -> 1), bit0=leftmost,
    shifted right by SHIFT px. Row 0 of the PNG grid = the filled art."""
    ox, oy = col * 16, 0
    out = []
    for y in range(16):
        b = [0, 0, 0]
        for x in range(16):
            r, g, bl, a = im.getpixel((ox + x, oy + y))
            if a < 128:
                continue               # transparent -> not part of the piece
            p = x + SHIFT              # absolute pixel column 0..17
            byte = p // 7              # 7 pixels per HGR byte
            bit = p % 7                # bit 0 = leftmost
            b[byte] |= (1 << bit)
        out.extend(b)
    return out


def fmt(bs: list[int]) -> str:
    lines = []
    for r in range(16):
        i = r * 3
        lines.append("        .byte " + ", ".join(f"${v:02X}" for v in bs[i:i + 3])
                     + f"   ; row {r:02d}")
    return "\n".join(lines)


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    exports = ", ".join(f"chess_{n}_mask" for n in NAMES)
    parts = [
        "; ============================================================================",
        "; chess_hgr_masks.asm  --  6 silhouette masks (16x16) for HGR chess",
        "; Generated by tools/build_chess_hgr_masks.py from pic/chess_pieces_16x16.png.",
        "; DO NOT EDIT BY HAND -- rerun the generator instead.",
        "; ----------------------------------------------------------------------------",
        "; One silhouette mask per piece type. 16 rows x 3 bytes; bit 0 = leftmost",
        "; pixel, 7 px/byte (bits 0..6), bit 7 clear. 1 = piece pixel. The 16-px",
        f"; silhouette is shifted right {SHIFT} px to centre it in a 21-px (3-byte) square.",
        "; The renderer paints these pixels BLACK (clear) or ORANGE (stamp) over the",
        "; already-drawn square colour, so ONE mask serves both sides.",
        "; ============================================================================",
        "; Emitted into CODE so the sketch can `.include` this file directly into a",
        "; single self-contained assembly unit (no external link step).",
        f".export {exports}",
        "",
        ".segment \"CODE\"",
        "",
    ]
    for col, name in enumerate(NAMES):
        bs = mask_bytes(im, col)
        parts.append(f"; {name}")
        parts.append(f"chess_{name}_mask:")
        parts.append(fmt(bs))
        parts.append("")
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT} ({len(NAMES)} masks, shift={SHIFT})")


if __name__ == "__main__":
    main()
