#!/usr/bin/env python3
"""
Extract an ASCII $20-$5F subset (space .. '_') of the Beautiful Boot HGR font
into dev/lib/gen2/bbfont_ascii5f.inc.

The master dev/lib/gen2/bbfont_cp437.inc is a full 256-glyph CP437 table
(2 KB). Small HGR programs that only print uppercase text + digits (e.g. the
GEN2 chess move panel) don't want to link 2 KB of font, so this emits just the
64 printable glyphs $20..$5F as a contiguous table indexed by (char - $20).
Encoding is copied verbatim (8 bytes/glyph, bit 0 = leftmost, 8 rows top->
bottom), so a byte-aligned STA blitter can draw a glyph with no bit shifting.

Usage:  python3 tools/build_hgr_font_subset.py
"""
from __future__ import annotations
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC  = ROOT / "dev" / "lib" / "gen2" / "bbfont_cp437.inc"
OUT  = ROOT / "dev" / "lib" / "gen2" / "bbfont_ascii5f.inc"

LO, HI = 0x20, 0x5F      # inclusive range (space .. '_')


def main() -> None:
    # Parse ".byte b0,..,b7 ; $XX ..." lines into glyphs keyed by code.
    glyphs: dict[int, list[str]] = {}
    line_re = re.compile(r"\.byte\s+(.+?)\s*;\s*\$([0-9A-Fa-f]{2})")
    for line in SRC.read_text().splitlines():
        m = line_re.search(line)
        if not m:
            continue
        code = int(m.group(2), 16)
        bytes_ = [b.strip() for b in m.group(1).split(",")]
        if len(bytes_) == 8:
            glyphs[code] = bytes_

    missing = [c for c in range(LO, HI + 1) if c not in glyphs]
    if missing:
        raise SystemExit(f"master font missing codes: {[hex(c) for c in missing]}")

    out = [
        "; =============================================================================",
        "; bbfont_ascii5f.inc -- ASCII $20-$5F subset of the Beautiful Boot HGR font.",
        "; Generated by tools/build_hgr_font_subset.py from bbfont_cp437.inc.",
        "; DO NOT EDIT BY HAND -- rerun the generator instead.",
        "; -----------------------------------------------------------------------------",
        "; 64 printable glyphs (space .. '_'), 8 bytes each, bit 0 = leftmost pixel,",
        "; 8 rows top->bottom. Index a glyph by (char - $20). Byte-aligned STA blit.",
        "; =============================================================================",
        "",
        "HGR_FONT5F_BYTES_PER_GLYPH = 8",
        "HGR_FONT5F_FIRST_CHAR      = $20",
        "",
        "HGR_Font5F:",
    ]
    for code in range(LO, HI + 1):
        ch = chr(code) if code != 0x20 else " "
        disp = "SPACE" if code == 0x20 else f"'{ch}'"
        out.append(f"        .byte {','.join(glyphs[code])}  ; ${code:02X} {disp}")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} ({HI - LO + 1} glyphs, $%02X..$%02X)" % (LO, HI))


if __name__ == "__main__":
    main()
