#!/usr/bin/env python3
# ============================================================================
# build_c64font_tms.py -- emit dev/lib/tms9918/c64font_tms.inc from the C64
# font master in dev/lib/tms9918c/c64font.c.
# ----------------------------------------------------------------------------
# The Applesoft TMS9918 console (sketchs/tms9918/applesoft_tms9918) runs the VDP
# in Text Mode F1: 40x24 cells, but the chip (and POM1's renderer,
# TMS9918.cpp renderTextLineRaw) display only the LEFTMOST 6 pixels of each 8-bit
# pattern byte -- pattern bits 7..2; bits 1..0 are never shown.
#
# The C64 font is an 8-pixel outline font centred in the cell (glyph content in
# bits 6..1). Uploaded verbatim it would sit one pixel right of centre AND lose
# its rightmost column on every glyph. So each byte is shifted LEFT one bit
# ((b << 1) & 0xFF): the C64 content (bits 6..1) lands in the 6 displayed columns
# (bits 7..2), reproducing the thin C64 look inside the 6px text cell. A handful
# of full-width glyphs (M, W, the box-drawing slots) lose 1px on the right; that
# is inherent to fitting an 8px font into a 6px cell and is barely visible.
#
# Output matches bbfont_tms.inc's shape: label `tms_c64font`, 96 glyphs
# (ASCII $20-$7F), 8 bytes/glyph, MSB = leftmost pixel. `.include` it at the
# pattern-table spot in the ROM image and index (ch-$20)*8.
# ============================================================================
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "dev" / "lib" / "tms9918c" / "c64font.c"
OUT = ROOT / "dev" / "lib" / "tms9918" / "c64font_tms.inc"

FIRST_CHAR = 0x20
GLYPH_COUNT = 96
BYTES_PER_GLYPH = 8


def load_master():
    text = SRC.read_text()
    m = re.search(r"tms_c64font\[\d+\]\s*=\s*\{(.*?)\}", text, re.S)
    if not m:
        sys.exit(f"could not find tms_c64font[] array in {SRC}")
    nums = [int(n) for n in re.findall(r"\d+", m.group(1))]
    if len(nums) != GLYPH_COUNT * BYTES_PER_GLYPH:
        sys.exit(f"expected {GLYPH_COUNT*BYTES_PER_GLYPH} bytes, got {len(nums)}")
    return nums


def label(code):
    if code == 0x7F:
        return "?"
    if code == 0x27:
        return "'''"
    return f"'{chr(code)}'"


def main():
    raw = load_master()
    lines = []
    lines.append("; ============================================================================")
    lines.append("; c64font_tms.inc -- C64-style 8x8 font, TMS9918 Text-Mode pattern encoding.")
    lines.append("; GENERATED by tools/build_c64font_tms.py from dev/lib/tms9918c/c64font.c.")
    lines.append("; DO NOT EDIT -- rerun the tool to refresh after changing the master.")
    lines.append("; ----------------------------------------------------------------------------")
    lines.append("; ASCII 0x20-0x7F (96 glyphs), 8 bytes/glyph, MSB = leftmost pixel. The C64")
    lines.append("; master centres each glyph in 8 px (content in bits 6..1); TMS9918 Text Mode")
    lines.append("; F1 only displays the leftmost 6 px (pattern bits 7..2), so every byte is")
    lines.append("; shifted LEFT one bit here to land the glyph in the visible 6-px cell. This")
    lines.append("; is the thinner C64 alternative to the heavier bbfont_tms.inc.")
    lines.append(";")
    lines.append("; Inline data fragment (no .export, no .ifndef guard) -- `.include` it at the")
    lines.append("; pattern-table location in the ROM image, then index (ch-0x20)*8 like the C")
    lines.append("; runtime indexes c64font's FONT[]. cc65 include path: dev/lib/tms9918/.")
    lines.append("; ============================================================================")
    lines.append("")
    lines.append(f"TMS_C64FONT_FIRST_CHAR      = ${FIRST_CHAR:02X}")
    lines.append(f"TMS_C64FONT_GLYPH_COUNT     = {GLYPH_COUNT}")
    lines.append(f"TMS_C64FONT_BYTES_PER_GLYPH = {BYTES_PER_GLYPH}")
    lines.append("")
    lines.append("tms_c64font:")
    for g in range(GLYPH_COUNT):
        code = FIRST_CHAR + g
        glyph = raw[g * BYTES_PER_GLYPH:(g + 1) * BYTES_PER_GLYPH]
        shifted = [(b << 1) & 0xFF for b in glyph]
        data = ",".join(f"${b:02X}" for b in shifted)
        lines.append(f"        .byte {data} ; ${code:02X} {label(code)}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({GLYPH_COUNT} glyphs)")

    # Visual sanity dump for a few glyphs.
    for code in (0x41, 0x4F, 0x30, 0x21):  # A O 0 !
        g = code - FIRST_CHAR
        print(f"\n  ${code:02X} {chr(code)}")
        for b in raw[g * BYTES_PER_GLYPH:(g + 1) * BYTES_PER_GLYPH]:
            s = (b << 1) & 0xFF
            row = "".join("#" if s & (0x80 >> i) else "." for i in range(6))
            print(f"    {row}")


if __name__ == "__main__":
    main()
