#!/usr/bin/env python3
"""
Convert cc65-Chess's Apple II piece bitmaps (pieces.bin) into an asm include.

Source: StewBC/cc65-Chess  src/apple2/pieces.bin  (6 pieces x 2 variants x
22 rows x 3 bytes = 792 B). Piece art by Frank Gebhart (1980s); Apple II port
by Oliver Schmidt (2020); cc65-Chess by Stefan Wessels. HGR encoding: bit 0 =
leftmost pixel, 7 px/byte, bit 7 clear (monochrome; colour comes from the
copy/invert ROP + the black/white board, exactly as in cc65's platA2.c).

Piece order in the file = the cc65 `enum { NONE, ROOK, KNIGHT, BISHOP, QUEEN,
KING, PAWN }` (so index 0..5 = ROOK,KNIGHT,BISHOP,QUEEN,KING,PAWN). Two variants
per piece: [0] = outline (hollow), [1] = solid (filled).

Emits a flat table `cc65_pieces` + a 12-entry pointer table
`cc65_piece_lo/hi` indexed by (piece_idx*2 + variant), so the 6502 renderer
picks a bitmap with one table lookup (no *66 multiply).

Usage:  python3 tools/build_cc65_chess_pieces.py
"""
import pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC  = ROOT/"dev"/"lib"/"gen2"/"sprites"/"chess_cc65_pieces.bin"
OUT  = ROOT/"dev"/"lib"/"gen2"/"sprites"/"chess_cc65_pieces.asm"
W, H = 3, 22
GLYPH = W*H            # 66 bytes per variant bitmap
NAMES = ["rook","knight","bishop","queen","king","pawn"]

data = SRC.read_bytes()
assert len(data) == 6*2*GLYPH, f"unexpected size {len(data)}"

lines = [
"; ============================================================================",
"; chess_cc65_pieces.asm  --  cc65-Chess Apple II piece bitmaps (HGR).",
"; Generated by tools/build_cc65_chess_pieces.py from chess_cc65_pieces.bin.",
"; DO NOT EDIT BY HAND -- rerun the generator instead.",
"; ----------------------------------------------------------------------------",
"; Art: Frank Gebhart (1980s).  Apple II HGR port: Oliver Schmidt (2020).",
"; From Stefan Wessels' cc65-Chess (github.com/StewBC/cc65-Chess).",
"; 6 pieces x 2 variants x 22 rows x 3 bytes.  bit 0 = leftmost pixel, bit 7",
"; clear (monochrome -- colour is applied by the copy/invert ROP at blit time).",
"; Piece index 0..5 = ROOK,KNIGHT,BISHOP,QUEEN,KING,PAWN; variant 0 = outline,",
"; 1 = solid.  Table index = piece_idx*2 + variant.",
"; ============================================================================",
".export cc65_pieces, cc65_piece_lo, cc65_piece_hi",
"",
'.segment "CODE"',
"",
"cc65_pieces:",
]
for p in range(6):
    for v in range(2):
        base = (p*2+v)*GLYPH
        lines.append(f"; {NAMES[p]} {'outline' if v==0 else 'solid'} (idx {p*2+v})")
        blk = data[base:base+GLYPH]
        for r in range(H):
            row = blk[r*W:r*W+W]
            lines.append("        .byte " + ",".join(f"${b:02X}" for b in row))
lines.append("")
lines.append("cc65_piece_lo:")
lines.append("        .byte " + ", ".join(f"<(cc65_pieces+{(i)*GLYPH})" for i in range(12)))
lines.append("cc65_piece_hi:")
lines.append("        .byte " + ", ".join(f">(cc65_pieces+{(i)*GLYPH})" for i in range(12)))
OUT.write_text("\n".join(lines)+"\n")
print(f"wrote {OUT} ({len(data)} bytes, 12 variants)")
