#!/usr/bin/env python3
"""build_shared_font.py — one Beautiful Boot glyph master → per-card font tables.

Axis 2 of the GEN2/TMS9918 library factoring (see sketchs/doc/TODO6502.md). The single
source of truth for the Beautiful Boot 8x8 font is the asm glyph master

    dev/lib/gen2/bbfont_cp437.inc  (256 glyphs, 8 rows, bit 0 = LEFTMOST pixel,
                                    values <= 0x7F → 7 px/byte HGR encoding)

This tool mirrors tools/build_hgr_sprites.py (one master → emitters per format,
with a --check mode) and supersedes the older tools/emit_bbfont.py (which only
emitted the HGR slice). Emitters:

    hgr  -> dev/lib/gen2c/gen2_bbfont.inc    HGR C fragment, ASCII 0x20-0x7F,
                                             bit 0 = left (gen2.c #includes it).
    tms  -> dev/lib/tms9918/bbfont_tms.inc   TMS9918 pattern table, ASCII
                                             0x20-0x7F, bit 7 = left, asm.
    hud  -> dev/lib/tms9918/font_hud8x8.inc  TMS9918 HUD subset (char codes
                                             56..92), bit 7 = left, asm.
    cpp  -> src/hgrpaint/HgrFont.cpp          full CP437 (256 glyphs) C++ table for
                                             the HGR Paint editor's Text tool,
                                             bit 0 = left (host-side, not 6502).

ENCODING. The TMS9918 pattern table wants the leftmost pixel in bit 7, the HGR
card wants it in bit 0. So the TMS byte is the BIT-REVERSE of the HGR byte:
master bit 0 (left) → TMS bit 7 (left); the empty 8th column of the 7-px BB
glyph lands in bit 0 (a 1-px inter-char gap). One master, two encodings, zero
hand-copying — the HGR and TMS fonts can no longer silently drift.

Usage:
    python3 tools/build_shared_font.py            # rebuild all three
    python3 tools/build_shared_font.py --only tms
    python3 tools/build_shared_font.py --check    # diff vs on-disk (CI / regression)
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Dict, List

REPO = pathlib.Path(__file__).resolve().parents[1]
MASTER = REPO / "dev" / "lib" / "gen2" / "bbfont_cp437.inc"
OUT_HGR = REPO / "dev" / "lib" / "gen2c" / "gen2_bbfont.inc"
OUT_TMS = REPO / "dev" / "lib" / "tms9918" / "bbfont_tms.inc"
OUT_HUD = REPO / "dev" / "lib" / "tms9918" / "font_hud8x8.inc"
OUT_CPP = REPO / "src" / "hgrpaint" / "HgrFont.cpp"

BYTE_RE = re.compile(r"\$([0-9A-Fa-f]{2})")
IDX_RE = re.compile(r";\s*\$([0-9A-Fa-f]{2})")

# HUD subset: TMS char codes 56..92 used by the Snake/Sokoban score/title text,
# in their on-ROM order. Each maps to the ASCII glyph pulled from the master.
# (The two slim '(' / ')' glyphs, char 93/94, stay project-local overrides.)
HUD_FIRST_CODE = 56
HUD_CHARS = "MV:0123456789SOKBANPREL GHTDYIUQWZCXF"


def parse_master(src: pathlib.Path) -> Dict[int, List[int]]:
    """master .inc → {glyph code: [8 row bytes]} (bit 0 = leftmost pixel)."""
    glyphs: Dict[int, List[int]] = {}
    for line in src.read_text().splitlines():
        s = line.strip()
        if not s.startswith(".byte"):
            continue
        vals = [int(h, 16) for h in BYTE_RE.findall(s.split(";", 1)[0])]
        m = IDX_RE.search(line)
        if m is None or len(vals) != 8:
            continue
        glyphs[int(m.group(1), 16)] = vals
    return glyphs


def rev8(b: int) -> int:
    """Bit-reverse a byte: HGR bit 0 (left) → TMS bit 7 (left)."""
    return int(f"{b & 0xFF:08b}"[::-1], 2)


def _need(glyphs: Dict[int, List[int]], code: int) -> List[int]:
    if code not in glyphs:
        raise SystemExit(f"missing glyph 0x{code:02X} in {MASTER.name}")
    return glyphs[code]


def _ascii_label(code: int) -> str:
    return f"'{chr(code)}'" if 0x21 <= code <= 0x7E else "' '" if code == 0x20 else "?"


def emit_hgr(glyphs: Dict[int, List[int]]) -> str:
    """gen2_bbfont.inc — HGR C fragment, bit 0 = left, ASCII 0x20-0x7F."""
    out = [
        "/* gen2_bbfont.inc - GENERATED by tools/build_shared_font.py. DO NOT EDIT.",
        " * Beautiful Boot 8x8 font, ASCII 0x20-0x7F (96 glyphs) - the ASCII slice of",
        " * dev/lib/gen2/bbfont_cp437.inc. bit 0 = leftmost pixel, rows top->bottom,",
        " * values <= 0x7F so each glyph fits HGR's 7 px/byte. */",
    ]
    for c in range(0x20, 0x80):
        row = ",".join(f"0x{b:02X}" for b in _need(glyphs, c))
        out.append(f"    {row},  /* 0x{c:02X} */")
    return "\n".join(out) + "\n"


def emit_tms(glyphs: Dict[int, List[int]]) -> str:
    """bbfont_tms.inc — TMS9918 pattern table, bit 7 = left, ASCII 0x20-0x7F."""
    out = [
        "; ============================================================================",
        "; bbfont_tms.inc -- Beautiful Boot 8x8 font, TMS9918 pattern-table encoding.",
        "; GENERATED by tools/build_shared_font.py from dev/lib/gen2/bbfont_cp437.inc.",
        "; DO NOT EDIT -- rerun the tool to refresh after changing the master.",
        "; ----------------------------------------------------------------------------",
        "; ASCII 0x20-0x7F (96 glyphs), 8 bytes/glyph, MSB = leftmost pixel (TMS pattern",
        "; table convention). This is the bit-reverse of the HGR 7 px/byte encoding in",
        "; gen2_bbfont.inc: master bit 0 (left) -> bit 7 (left); the empty 8th column of",
        "; the 7-px BB glyph lands in bit 0 (a 1-px inter-char gap).",
        ";",
        "; Inline data fragment (no .export, no .ifndef guard) -- `.include` it at the",
        "; pattern-table location in the ROM image, then index (ch-0x20)*8 like the C",
        "; runtime indexes c64font's FONT[]. cc65 include path: dev/lib/tms9918/.",
        "; ============================================================================",
        "",
        "TMS_BBFONT_FIRST_CHAR      = $20",
        "TMS_BBFONT_GLYPH_COUNT     = 96",
        "TMS_BBFONT_BYTES_PER_GLYPH = 8",
        "",
        "tms_bbfont:",
    ]
    for c in range(0x20, 0x80):
        row = ",".join(f"${rev8(b):02X}" for b in _need(glyphs, c))
        out.append(f"        .byte {row} ; ${c:02X} {_ascii_label(c)}")
    return "\n".join(out) + "\n"


def emit_hud(glyphs: Dict[int, List[int]]) -> str:
    """font_hud8x8.inc — TMS9918 HUD subset (char codes 56..92), bit 7 = left.

    Adopts the shared BB font on the TMS HUD path: the 37 glyphs Snake/Sokoban
    draw for score/title text now come from the single master (bit-reversed),
    in the same on-ROM order/codes as before so the games are unchanged but
    their text now matches the GEN2 BB font.
    """
    out = [
        "; ============================================================================",
        "; font_hud8x8.inc -- shared 8x8 HUD mini-font for TMS9918 games",
        "; GENERATED by tools/build_shared_font.py from dev/lib/gen2/bbfont_cp437.inc.",
        "; DO NOT EDIT -- rerun the tool to refresh after changing the master.",
        "; ----------------------------------------------------------------------------",
        "; The HUD overlay font the TMS9918 game ROMs (Snake, Sokoban) use to draw",
        "; on-screen score/title text. Each glyph is one 8x8 cell, MSB = leftmost pixel,",
        "; 1 byte per scanline (8 bytes/glyph) -- the bit-reverse of the master's HGR",
        "; 7 px/byte encoding, so the HUD now shares the Beautiful Boot font with the",
        "; GEN2 HGR side from a SINGLE source (Axe 2 of the lib factoring).",
        ";",
        "; Emits ONLY the 37 glyphs at TMS char codes 56..92, in their on-ROM order:",
        ";",
        ";     M V : 0 1 2 3 4 5 6 7 8 9 S O K B A N P R E L <space> G H T D Y I U Q",
        ";     W Z C X F",
        ";",
        "; The two slim parenthesis glyphs (char 93 '(' and char 94 ')') are NOT",
        "; included here -- each project keeps its own '(' / ')' as a LOCAL OVERRIDE",
        "; placed *immediately after* this include, so the on-ROM byte layout (char",
        "; 56..94 contiguous, 8 bytes each) is preserved exactly.",
        ";",
        "; Usage (both projects):",
        ";     hud_patterns:",
        ';             .include "font_hud8x8.inc"      ; emits chars 56..92 (tms_hud_font)',
        ";             ; char 93 '(' -- project-specific",
        ";             .byte ...",
        ";             ; char 94 ')' -- project-specific",
        ";             .byte ...",
        ";",
        "; `tms_hud_font` is a plain label before the data -- it adds no bytes, so",
        "; `hud_patterns` still points at char 56 and `hud_patterns+256` still indexes",
        "; the second VRAM copy half exactly as before. cc65 include path:",
        "; dev/lib/tms9918/  (-I ../../lib/tms9918). No .ifndef guard -- inline fragment",
        "; meant to be included exactly once at the font's location in the ROM image.",
        "; ============================================================================",
        "",
        "tms_hud_font:",
    ]
    for i, ch in enumerate(HUD_CHARS):
        code = HUD_FIRST_CODE + i
        glyph = _need(glyphs, ord(ch))
        row = ", ".join(f"${rev8(b):02X}" for b in glyph)
        label = "' '" if ch == " " else f"'{ch}'"
        out.append(f"        ; char {code} {label}")
        out.append(f"        .byte {row}")
    return "\n".join(out) + "\n"


def emit_cpp(glyphs: Dict[int, List[int]]) -> str:
    """HgrFont.cpp -- full CP437 256-glyph table for the HGR Paint editor.

    Host-side C++ (not 6502): the editor's Text tool stamps these glyphs into the
    HGR page through the pure model's plotPage(), so it lives in the portable
    src/hgrpaint/ toolkit. Same encoding as the master: bit 0 = leftmost pixel, rows
    top->bottom, 7 px/glyph (values <= 0x7F). Declared in HgrFont.h.
    """
    out = [
        "// Pom1 Apple 1 Emulator",
        "// Copyright (C) 2000-2026 Verhille Arnaud",
        "//",
        "// HgrFont.cpp -- GENERATED by tools/build_shared_font.py. DO NOT EDIT.",
        "// Beautiful Boot 8x8 font, full CP437 (256 glyphs), from the single master",
        "// dev/lib/gen2/bbfont_cp437.inc. bit 0 = leftmost pixel, rows top->bottom,",
        "// 7 px/glyph. Used by the HGR Paint editor's Text tool (see HgrFont.h).",
        "",
        '#include "HgrFont.h"',
        "",
        "namespace hgrpaint {",
        "",
        "const uint8_t kBBFontCp437[256][8] = {",
    ]
    for c in range(0x100):
        row = ", ".join(f"0x{b:02X}" for b in _need(glyphs, c))
        out.append(f"    {{ {row} }},  // 0x{c:02X} {_ascii_label(c)}")
    out.append("};")
    out.append("")
    out.append("} // namespace hgrpaint")
    return "\n".join(out) + "\n"


EMITTERS = {
    "hgr": (OUT_HGR, emit_hgr),
    "tms": (OUT_TMS, emit_tms),
    "hud": (OUT_HUD, emit_hud),
    "cpp": (OUT_CPP, emit_cpp),
}


def main(argv: List[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--only", choices=sorted(EMITTERS),
                   help="rebuild a single target (hgr / tms / hud)")
    p.add_argument("--check", action="store_true",
                   help="diff regenerated output against on-disk files (exit 1 on drift)")
    args = p.parse_args(argv)

    glyphs = parse_master(MASTER)
    targets = [args.only] if args.only else list(EMITTERS)

    diff = 0
    for name in targets:
        path, emit = EMITTERS[name]
        new = emit(glyphs)
        if args.check:
            old = path.read_text() if path.exists() else ""
            if old != new:
                print(f"[diff] {path.relative_to(REPO)} differs", file=sys.stderr)
                diff += 1
            else:
                print(f"[ok]   {path.relative_to(REPO)}", file=sys.stderr)
            continue
        path.write_text(new)
        print(f"[write] {path.relative_to(REPO)}", file=sys.stderr)

    if args.check:
        return 1 if diff else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
