#!/usr/bin/env python3
"""
Generate dev/lib/tms9918/sprites_chess.asm from pic/chess_pieces_16x16.png.

Source art: a 96x32 one-bit chess set, 6 columns x 2 rows of 16x16 cells:
  row 0 = "filled" pieces, row 1 = the exact colour-inverse ("outline").
Column order: pawn, knight, bishop, rook, queen, king.

The two rows share the SAME silhouette (they differ only in which pixels are
ink vs fill), so for a monochrome TMS9918 sprite/pattern we emit ONE pattern
per piece type = the silhouette (any non-transparent pixel -> bit 1). The
side colour (white vs black) is applied at render time via the TMS9918
colour table, so a single pattern serves both colours.

Output format mirrors dev/lib/tms9918/sprites_fauna.asm (native 16x16 TMS
sprite: 16 bytes left half col 0..7, then 16 bytes right half col 8..15;
MSB = leftmost pixel). Dual labels (bare + _-prefixed) for asm and cc65.

Usage:  python3 tools/build_chess_sprites.py
"""
from __future__ import annotations
import pathlib
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC  = ROOT / "pic" / "chess_pieces_16x16.png"
OUT  = ROOT / "dev" / "lib" / "tms9918" / "sprites_chess.asm"

NAMES = ["pawn", "knight", "bishop", "rook", "queen", "king"]


def piece_bytes(im: Image.Image, col: int, row: int) -> list[int]:
    """32 native-TMS bytes for the 16x16 silhouette at grid (col,row)."""
    ox, oy = col * 16, row * 16
    out = []
    for half in (0, 8):                       # left cols 0..7, then right 8..15
        for y in range(16):
            b = 0
            for bit in range(8):
                x = half + bit
                _, _, _, a = im.getpixel((ox + x, oy + y))
                if a >= 128:                  # non-transparent -> ink
                    b |= 0x80 >> bit
            out.append(b)
    return out


def fmt(bs: list[int]) -> str:
    lines = []
    for i in range(0, 32, 8):
        lines.append("        .byte " + ", ".join(f"${v:02X}" for v in bs[i:i + 8]))
    return "\n".join(lines)


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    exports = ", ".join(f"_chess_{n}_pat" for n in NAMES)
    exports2 = ", ".join(f"chess_{n}_pat" for n in NAMES)
    parts = [
        "; ============================================================================",
        "; sprites_chess.asm  --  6 sprites (16x16, TMS9918 sprite/pattern mode)",
        "; Generated by tools/build_chess_sprites.py from pic/chess_pieces_16x16.png.",
        "; DO NOT EDIT BY HAND -- rerun the generator instead.",
        "; ----------------------------------------------------------------------------",
        "; One monochrome SILHOUETTE pattern per piece type (pawn,knight,bishop,rook,",
        "; queen,king). The side colour (white/black) is set at render time via the",
        "; TMS9918 colour table, so a single pattern serves both colours.",
        ";",
        "; Native TMS9918 16x16 layout: 32 bytes per piece -- first 16 = left half",
        "; (col 0..7), next 16 = right half (col 8..15); MSB = leftmost pixel.",
        "; ============================================================================",
        f".export {exports}",
        f".export {exports2}",
        "",
        ".segment \"CODE\"",
        "",
    ]
    for col, name in enumerate(NAMES):
        bs = piece_bytes(im, col, 0)          # row 0 (silhouette == row 1 silhouette)
        parts.append(f"; {name} (silhouette)")
        parts.append(f"chess_{name}_pat:")
        parts.append(f"_chess_{name}_pat:")
        parts.append(fmt(bs))
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT} ({len(NAMES)} pieces)")


if __name__ == "__main__":
    main()
