#!/usr/bin/env python3
"""
Convertit la planche PNG « offline dinosaur » de Chromium (LDPI) en motifs
sprite TMS9918A 16×16 (32 octets / motif, ordre UL, UR, LL, LR).

Source planche (BSD Chromium) :
  https://raw.githubusercontent.com/chromium/chromium/main/components/neterror/resources/images/default_100_percent/offline/100-offline-sprite.png

Découpes alignées sur :
  dino_game/offline_sprite_definitions.ts (tRex ldpi x,y)
  dino_game/trex.ts (animFrames + dimensions)

Usage :
  python3 tools/chrome_dino_sheet_to_tms.py [--png PATH] [--out PATH]

Sans --png : télécharge l’URL officielle (nécessite urllib ; Pillow requis).
"""
from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

# Coordonnées LDPI (100-offline-sprite.png) — offline_sprite_definitions.ts
TREX_ORIGIN_X = 848
TREX_ORIGIN_Y = 2
# trex.ts defaultTrexConfig + animFrames (offsets horizontaux relatifs)
TREX_W, TREX_H = 44, 47
FRAMES = {
    "run0": (88, TREX_W, TREX_H),
    "run1": (132, TREX_W, TREX_H),
    "jump": (0, TREX_W, TREX_H),
}
# cactusSmall — offline_sprite_definitions obstacles + sprite cactusSmall
CACTUS_X, CACTUS_Y = 228, 2
CACTUS_W, CACTUS_H = 17, 35

DEFAULT_URL = (
    "https://raw.githubusercontent.com/chromium/chromium/main/"
    "components/neterror/resources/images/default_100_percent/offline/"
    "100-offline-sprite.png"
)


def load_png(path: Path | None, url: str) -> "object":
    try:
        from PIL import Image
    except ImportError as e:
        raise SystemExit(
            "Pillow est requis : pip install Pillow\n" + str(e)
        ) from e
    if path and path.is_file():
        data = path.read_bytes()
    else:
        req = urllib.request.Request(
            url, headers={"User-Agent": "POM1-chrome_dino_sheet_to_tms/1.0"}
        )
        with urllib.request.urlopen(req, timeout=30) as r:
            data = r.read()
    import io

    return Image.open(io.BytesIO(data)).convert("RGBA")


def bbox_to_mask16(img, left: int, top: int, w: int, h: int) -> list[list[int]]:
    """Découpe, redimensionne 16×16 (nearest), binarise → grille 0/1."""
    from PIL import Image

    crop = img.crop((left, top, left + w, top + h))
    crop = crop.resize((16, 16), Image.Resampling.NEAREST)
    px = crop.load()
    grid: list[list[int]] = []
    for y in range(16):
        row = []
        for x in range(16):
            r, g, b, a = px[x, y]
            # Silhouette sombre sur fond clair dans la planche Chrome
            dark = (r + g + b) < 3 * 128
            opaque = a > 128
            row.append(1 if (opaque and dark) else 0)
        grid.append(row)
    return grid


def mask16_to_tms32(grid: list[list[int]]) -> bytes:
    """4 blocs 8×8 : HG, HD, BG, BD — bit 7 = colonne de gauche (TMS)."""
    out = bytearray()

    def pack_quad(y0: int, x0: int) -> bytes:
        b = bytearray()
        for dy in range(8):
            rowb = 0
            for dx in range(8):
                if grid[y0 + dy][x0 + dx]:
                    rowb |= 0x80 >> dx
            b.append(rowb)
        return bytes(b)

    out += pack_quad(0, 0)  # UL
    out += pack_quad(0, 8)  # UR
    out += pack_quad(8, 0)  # LL
    out += pack_quad(8, 8)  # LR
    assert len(out) == 32
    return bytes(out)


def emit_c_header(patterns: dict[str, bytes], out: Path) -> None:
    lines = [
        "/* Auto-generated by tools/chrome_dino_sheet_to_tms.py - do not edit. */",
        "/* Sprite sheet: Chromium 100-offline-sprite.png (BSD). */",
        "#ifndef DINO_CHROME_TMS_H",
        "#define DINO_CHROME_TMS_H",
        "",
    ]
    for name, raw in patterns.items():
        lines.append(f"static const unsigned char pat_{name}[32] = {{")
        for i in range(0, 32, 8):
            chunk = ", ".join(f"0x{b:02X}U" for b in raw[i : i + 8])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")
    lines.extend(
        [
            "/* TMS 16x16 pattern indices (multiple of 4). */",
            "#define PAT_CHROME_RUN0   0U",
            "#define PAT_CHROME_RUN1   4U",
            "#define PAT_CHROME_JUMP   8U",
            "#define PAT_CHROME_CACTUS 12U",
            "",
            "#endif",
            "",
        ]
    )
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--png", type=Path, default=None, help="Planche LDPI locale")
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "dev/apple1-videocard-lib/demos/chrome_dino/dino_chrome_tms.h",
        help="Fichier .h de sortie",
    )
    ap.add_argument("--url", default=DEFAULT_URL)
    args = ap.parse_args()

    img = load_png(args.png, args.url)
    patterns: dict[str, bytes] = {}
    for key, (dx, w, h) in FRAMES.items():
        left = TREX_ORIGIN_X + dx
        top = TREX_ORIGIN_Y
        g = bbox_to_mask16(img, left, top, w, h)
        patterns[f"chrome_{key}"] = mask16_to_tms32(g)

    g_c = bbox_to_mask16(img, CACTUS_X, CACTUS_Y, CACTUS_W, CACTUS_H)
    patterns["chrome_cactus"] = mask16_to_tms32(g_c)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    emit_c_header(patterns, args.out)
    print(f"Wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
