#!/usr/bin/env python3
"""Generate dev/lib/gen2c/gen2_bbfont.inc from dev/lib/hgr/bbfont_cp437.inc.

The GEN2 C runtime (gen2.c) draws text with the Beautiful Boot 8x8 font via
gen2_hgr_puts. That glyph data is exactly the ASCII slice (0x20-0x7F) of the
canonical asm table bbfont_cp437.inc. Rather than hand-copy 768 bytes into the C
file (and let the two silently drift), gen2.c #includes the generated body this
script emits from the single source.

Re-run after editing the font:  python3 tools/emit_bbfont.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "dev" / "lib" / "hgr" / "bbfont_cp437.inc"
OUT = ROOT / "dev" / "lib" / "gen2c" / "gen2_bbfont.inc"

BYTE_RE = re.compile(r"\$([0-9A-Fa-f]{2})")
IDX_RE = re.compile(r";\s*\$([0-9A-Fa-f]{2})")


def parse(src: pathlib.Path) -> dict:
    glyphs = {}
    for line in src.read_text().splitlines():
        s = line.strip()
        if not s.startswith(".byte"):
            continue
        code = s.split(";", 1)[0]
        vals = [int(h, 16) for h in BYTE_RE.findall(code)]
        m = IDX_RE.search(line)
        if m is None or len(vals) != 8:
            continue
        glyphs[int(m.group(1), 16)] = vals
    return glyphs


def main() -> int:
    glyphs = parse(SRC)
    out = [
        "/* gen2_bbfont.inc - GENERATED by tools/emit_bbfont.py. DO NOT EDIT.",
        " * Beautiful Boot 8x8 font, ASCII 0x20-0x7F (96 glyphs) - the ASCII slice of",
        " * dev/lib/hgr/bbfont_cp437.inc. bit 0 = leftmost pixel, rows top->bottom,",
        " * values <= 0x7F so each glyph fits HGR's 7 px/byte. */",
    ]
    for c in range(0x20, 0x80):
        if c not in glyphs:
            print(f"missing glyph 0x{c:02X} in {SRC}", file=sys.stderr)
            return 1
        row = ",".join(f"0x{b:02X}" for b in glyphs[c])
        out.append(f"    {row},  /* 0x{c:02X} */")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} ({0x80 - 0x20} glyphs from {SRC.name})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
