#!/usr/bin/env python3
"""
gen_zp_map.py -- machine-generate the cross-library zero-page map tables in
dev/lib/README.md from the actual sources.

The ZP map used to be hand-written and drifted (modules like gen2/hgr_plot.asm
were missing). This script parses every dev/lib/**/*.asm|.s|.inc for:

  - `.segment "ZEROPAGE"` / `.zeropage` blocks -> `label: .res N` reservations
  - `.importzp` / `.exportzp` symbol lists
  - hardcoded ZP equates  `name := $xx`  (value < $100)

and rewrites the two tables between the ZPMAP markers in dev/lib/README.md:

  <!-- ZPMAP:BASELINE:BEGIN --> ... <!-- ZPMAP:BASELINE:END -->
      the fixed $00-$07 zp.inc baseline (addresses derived from declaration
      order in apple1/zp.inc -- the same positional contract the zp_layout
      test pins)
  <!-- ZPMAP:FLOATING:BEGIN --> ... <!-- ZPMAP:FLOATING:END -->
      one row per module that reserves/imports ZP by name

Everything outside the markers (the RULES prose, the collision registry) stays
hand-written. Human annotations (owners, "not live across calls" notes,
caller-defined include contracts) live in tools/zp_annotations.json and are
merged into the generated output -- regeneration never loses them. Annotation
keys that no longer match any scanned module are reported as a warning so the
sidecar can be pruned.

Usage:
  tools/gen_zp_map.py            # regenerate the tables in dev/lib/README.md
  tools/gen_zp_map.py --check    # exit 1 if the README tables have drifted
                                 # (wire to CI/ctest)
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LIB = REPO / "dev" / "lib"
README = LIB / "README.md"
ANNOTATIONS = Path(__file__).resolve().parent / "zp_annotations.json"
BASELINE_FILE = "apple1/zp.inc"

MARK = {
    "baseline": ("<!-- ZPMAP:BASELINE:BEGIN (generated by tools/gen_zp_map.py"
                 " -- edit tools/zp_annotations.json, not this table) -->",
                 "<!-- ZPMAP:BASELINE:END -->"),
    "floating": ("<!-- ZPMAP:FLOATING:BEGIN (generated by tools/gen_zp_map.py"
                 " -- edit tools/zp_annotations.json, not this table) -->",
                 "<!-- ZPMAP:FLOATING:END -->"),
}

RE_SEGMENT = re.compile(r'^\s*\.segment\s+"([^"]+)"', re.I)
RE_ZPSHORT = re.compile(r"^\s*\.(zeropage|code|data|bss|rodata)\b", re.I)
RE_RES = re.compile(r"^\s*(@?\w+):\s*\.res\s+(\$[0-9A-Fa-f]+|\d+)", re.I)
RE_IMPORTZP = re.compile(r"^\s*\.importzp\s+(.+)$", re.I)
RE_EXPORTZP = re.compile(r"^\s*\.exportzp\s+(.+)$", re.I)
# ZP equate: label := $xx with a 1-2 digit hex value (an *address* assignment;
# plain `=` is a numeric constant in ca65 and would false-positive on colour/
# geometry constants).
RE_ZPEQU = re.compile(r"^\s*(\w+)\s*:=\s*\$([0-9A-Fa-f]{1,2})\s*$")


def strip_comment(line: str) -> str:
    return line.split(";", 1)[0]


def parse_size(tok: str) -> int:
    return int(tok[1:], 16) if tok.startswith("$") else int(tok)


def scan_file(path: Path) -> dict:
    """Return {'res': [(name, size)], 'importzp': [..], 'exportzp': [..],
    'equates': [(name, addr)]} for one source file."""
    res, imps, exps, equs = [], [], [], []
    seg = "CODE"
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = strip_comment(raw).rstrip()
        if not line:
            continue
        m = RE_SEGMENT.match(line)
        if m:
            seg = m.group(1).upper()
            continue
        m = RE_ZPSHORT.match(line)
        if m:
            seg = m.group(1).upper()
            continue
        m = RE_IMPORTZP.match(line)
        if m:
            imps += [s.strip() for s in m.group(1).split(",") if s.strip()]
            continue
        m = RE_EXPORTZP.match(line)
        if m:
            exps += [s.strip() for s in m.group(1).split(",") if s.strip()]
            continue
        m = RE_ZPEQU.match(line)
        if m:
            equs.append((m.group(1), int(m.group(2), 16)))
            continue
        if seg == "ZEROPAGE":
            m = RE_RES.match(line)
            if m:
                res.append((m.group(1), parse_size(m.group(2))))
    return {"res": res, "importzp": imps, "exportzp": exps, "equates": equs}


def scan_tree() -> dict[str, dict]:
    """Scan dev/lib recursively; key = path relative to dev/lib (posix)."""
    out = {}
    for path in sorted(LIB.rglob("*")):
        if path.suffix.lower() not in (".asm", ".s", ".inc"):
            continue
        rel = path.relative_to(LIB).as_posix()
        if "/test/" in f"/{rel}":          # per-lib test fixtures/probes
            continue
        info = scan_file(path)
        if info["res"] or info["importzp"] or info["equates"]:
            out[rel] = info
    return out


def load_annotations() -> dict:
    if ANNOTATIONS.exists():
        return json.loads(ANNOTATIONS.read_text(encoding="utf-8"))
    return {"baseline": {}, "files": {}}


def fmt_slots(info: dict) -> str:
    parts = []
    for name, size in info["res"]:
        parts.append(f"`{name}`" if size == 1 else f"`{name}[{size}]`")
    for name, addr in info["equates"]:
        parts.append(f"`{name}` := `${addr:02X}` (fixed)")
    s = ", ".join(parts) if parts else "—"
    if info["res"] and info["exportzp"]:
        exported = [n for n, _ in info["res"] if n in info["exportzp"]]
        if exported:
            tag = "all" if len(exported) == len(info["res"]) else \
                  ", ".join(f"`{n}`" for n in exported)
            s += f" ({tag} `.exportzp`'d)"
    return s


def fmt_imports(info: dict) -> str:
    if not info["importzp"]:
        return "—"
    return ", ".join(f"`{n}`" for n in dict.fromkeys(info["importzp"]))


def build_tables(modules: dict[str, dict], ann: dict) -> tuple[str, str]:
    # --- baseline: fixed addresses from zp.inc declaration order -----------
    base = modules.get(BASELINE_FILE)
    if base is None:
        sys.exit(f"ERROR: baseline {BASELINE_FILE} not found under {LIB}")
    rows = ["| Addr | Symbol | Owner / users |", "|---|---|---|"]
    addr = 0
    for name, size in base["res"]:
        a = f"`${addr:02X}`" if size == 1 else \
            f"`${addr:02X}-${addr + size - 1:02X}`"
        note = ann.get("baseline", {}).get(name, "")
        rows.append(f"| {a} | `{name}` | {note} |")
        addr += size
    baseline_md = "\n".join(rows)

    # --- floating: one row per module --------------------------------------
    rows = ["| Lib | Own ZP slots (`.res` in `ZEROPAGE` / fixed equates)"
            " | `.importzp` | Notes |",
            "|---|---|---|---|"]
    file_ann = ann.get("files", {})
    # extra_modules: textual includes that use CALLER-defined bare symbols
    # (no .res / .importzp of their own -- invisible to the parser). The
    # sidecar supplies their contract: {"slots": "...", "notes": "..."}.
    extra = ann.get("extra_modules", {})
    names = sorted(set(k for k in modules if k != BASELINE_FILE) | set(extra))
    for rel in names:
        if rel in modules:
            info = modules[rel]
            slots, imports = fmt_slots(info), fmt_imports(info)
            note = file_ann.get(rel, "")
        else:
            slots = extra[rel].get("slots", "—")
            imports = extra[rel].get("importzp", "—")
            note = extra[rel].get("notes", "")
        rows.append(f"| [`{rel}`]({rel}) | {slots} | {imports} | {note} |")
    floating_md = "\n".join(rows)
    return baseline_md, floating_md


def splice(text: str, key: str, body: str) -> str:
    begin, end = MARK[key]
    i, j = text.find(begin), text.find(MARK[key][1])
    if i < 0 or j < 0 or j < i:
        sys.exit(f"ERROR: {README} is missing the {begin!r} / {end!r} markers"
                 " -- re-add them around the generated table")
    return text[:i] + begin + "\n" + body + "\n" + text[j:]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--check", action="store_true",
                    help="diff against the README instead of rewriting;"
                         " exit 1 on drift")
    args = ap.parse_args()

    modules = scan_tree()
    ann = load_annotations()

    stale = [k for k in ann.get("files", {}) if k not in modules]
    stale += [k for k in ann.get("extra_modules", {})
              if not (LIB / k).exists()]
    for k in stale:
        print(f"WARNING: zp_annotations.json entry {k!r} matches no scanned"
              " module (renamed/deleted? prune the sidecar)", file=sys.stderr)

    baseline_md, floating_md = build_tables(modules, ann)
    current = README.read_text(encoding="utf-8")
    updated = splice(splice(current, "baseline", baseline_md),
                     "floating", floating_md)

    if args.check:
        if updated != current:
            print(f"DRIFT: {README} ZP tables are stale -- run"
                  " tools/gen_zp_map.py to regenerate. Diff:")
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(keepends=True),
                updated.splitlines(keepends=True),
                fromfile="README.md (committed)",
                tofile="README.md (regenerated)"))
            return 1
        print(f"OK: {README} ZP tables match the sources"
              f" ({len(modules)} modules scanned)")
        return 0

    if updated != current:
        README.write_text(updated, encoding="utf-8")
        print(f"regenerated ZP tables in {README} ({len(modules)} modules)")
    else:
        print(f"{README} already up to date ({len(modules)} modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
