#!/usr/bin/env python3
"""Emit C byte arrays from sketchs/tms9918/game_rogue/tileset_rogue.inc."""
from __future__ import annotations

import re
import sys
from pathlib import Path


def parse_bytes(block: str) -> list[int]:
    out: list[int] = []
    for line in block.splitlines():
        if ".byte" not in line:
            continue
        m = re.search(r"\.byte\s+(.+)$", line)
        if not m:
            continue
        for part in m.group(1).split(","):
            part = part.strip().split(";")[0].strip()
            if not part:
                continue
            if part.startswith("$"):
                out.append(int(part[1:], 16))
            else:
                raise ValueError(f"unexpected token {part!r}")
    return out


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    inc = root / "sketchs/tms9918/game_rogue/tileset_rogue.inc"
    out_c = root / "dev/apple1-videocard-lib/demos/rogue_c/rogue_gfx_data.c"
    text = inc.read_text(encoding="utf-8")
    if "tileset_rogue:" not in text or "tileset_color_table:" not in text:
        print("markers missing", file=sys.stderr)
        return 1
    _, rest = text.split("tileset_rogue:", 1)
    tile_blob, colors_blob = rest.split("tileset_color_table:", 1)
    tile_bytes = parse_bytes(tile_blob)
    color_bytes = parse_bytes(colors_blob)
    if len(tile_bytes) != 2048:
        print(f"expected 2048 pattern bytes, got {len(tile_bytes)}", file=sys.stderr)
        return 1
    if len(color_bytes) != 32:
        print(f"expected 32 colour bytes, got {len(color_bytes)}", file=sys.stderr)
        return 1

    out_c.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Auto-generated by tools/rogue_tileset_inc_to_c.py — do not edit. */",
        '#include "rogue_gfx_data.h"',
        "",
        "const unsigned char rogue_tileset[2048] = {",
    ]
    for i in range(0, len(tile_bytes), 16):
        chunk = ", ".join(f"0x{b:02X}U" for b in tile_bytes[i : i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append("const unsigned char rogue_color_table[32] = {")
    lines.append("    " + ", ".join(f"0x{b:02X}U" for b in color_bytes))
    lines.append("};")
    lines.append("")
    lines.extend(
        [
            "/* char_paladin2_pat — TMS_Rogue.asm sprite_pats slot 0 */",
            "const unsigned char rogue_player_pat[32] = {",
            "    0x01U, 0x07U, 0x0FU, 0x0FU, 0x09U, 0x08U, 0x0EU, 0x02U,",
            "    0x7AU, 0x68U, 0x6BU, 0x6BU, 0x69U, 0x6AU, 0x34U, 0x00U,",
            "    0x82U, 0xE7U, 0xF0U, 0xF2U, 0x92U, 0x12U, 0x72U, 0x72U,",
            "    0x66U, 0x16U, 0xD8U, 0xE2U, 0x82U, 0x62U, 0x22U, 0x00U",
            "};",
            "",
        ]
    )
    out_c.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", out_c)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
