#!/usr/bin/env python3
"""Emit rogue_sprites_data.c from TMS_Rogue.asm (sprite_pats) + sprites_boss.asm."""
from __future__ import annotations

import re
import sys
from pathlib import Path


def parse_bytes_from_lines(lines: list[str]) -> list[int]:
    out: list[int] = []
    for line in lines:
        if ".byte" not in line:
            continue
        m = re.search(r"\.byte\s+(.+)$", line)
        if not m:
            continue
        for part in m.group(1).split(","):
            part = part.strip().split(";")[0].strip()
            if not part.startswith("$"):
                raise ValueError(part)
            out.append(int(part[1:], 16))
    return out


def extract_block(text: str, start_marker: str, end_marker: str) -> list[int]:
    i = text.index(start_marker) + len(start_marker)
    j = text.index(end_marker, i)
    return parse_bytes_from_lines(text[i:j].splitlines())


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    rogue_asm = (root / "dev/projects/tms9918_rogue/TMS_Rogue.asm").read_text(encoding="utf-8")
    boss_asm = (root / "dev/projects/tms9918_rogue/sprites_boss.asm").read_text(encoding="utf-8")
    out_c = root / "dev/apple1-videocard-lib/demos/rogue_c/rogue_sprites_data.c"

    # sprite_pats: from label through last torch .byte block (before prng16 include)
    sp = extract_block(rogue_asm, "\nsprite_pats:\n", "\n; prng16 --")
    if len(sp) != 448:
        print(f"expected 448 sprite_pats bytes, got {len(sp)}", file=sys.stderr)
        return 1
    boss = parse_bytes_from_lines(
        boss_asm.split("boss_sprite_pats:", 1)[1].split(".export", 1)[0].splitlines()
    )
    if len(boss) != 128:
        print(f"expected 128 boss bytes, got {len(boss)}", file=sys.stderr)
        return 1

    lines = [
        "/* Auto-generated by tools/rogue_sprites_to_c.py */",
        '#include "rogue_sprites_data.h"',
        "",
        "const unsigned char rogue_sprite_pats[448] = {",
    ]
    for i in range(0, 448, 16):
        lines.append("    " + ", ".join(f"0x{b:02X}U" for b in sp[i : i + 16]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("const unsigned char rogue_boss_sprite_pats[128] = {")
    for i in range(0, 128, 16):
        lines.append("    " + ", ".join(f"0x{b:02X}U" for b in boss[i : i + 16]) + ",")
    lines.append("};")
    lines.append("")
    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_c.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", out_c)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
