#!/usr/bin/env python3
"""RLE-encode Sokoban level data and emit ca65 .byte declarations.

RLE format:
  - byte < $80 : literal char (bit 7 always clear for Sokoban ASCII).
  - byte >= $80: (byte & $7F) = run length (2..127); next byte = char to repeat.
"""

import re
import sys
from pathlib import Path

ROOT = Path("/Users/factory/src/POM1/software")

def parse_levels(asm_path, start_n, end_n):
    """Return {n: (w, h, row_off, col_off, [rows])} for level<start>..level<end>."""
    text = asm_path.read_text()
    levels = {}
    for n in range(start_n, end_n + 1):
        # Match "levelN:\n    .byte W, H, RO, CO\n    .byte \"row0\"\n ..."
        pat = re.compile(
            rf'^level{n}:\s*\n'
            rf'\s*\.byte\s+(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\n'
            rf'((?:\s*\.byte\s+"[^"]*"\s*\n)+)',
            re.M,
        )
        m = pat.search(text)
        if not m:
            sys.exit(f"level{n} not found in {asm_path}")
        w, h, ro, co = (int(x) for x in m.group(1, 2, 3, 4))
        rows = re.findall(r'\.byte\s+"([^"]*)"', m.group(5))
        assert len(rows) == h, (asm_path, n, len(rows), h)
        for r in rows:
            assert len(r) == w, (asm_path, n, r, w)
        levels[n] = (w, h, ro, co, rows)
    return levels

def rle_encode(data: bytes) -> bytes:
    """Encode `data` into RLE form. Single-byte runs stay as literals."""
    out = bytearray()
    i = 0
    while i < len(data):
        c = data[i]
        # Count the run of identical bytes starting at i.
        j = i
        while j < len(data) and data[j] == c and (j - i) < 127:
            j += 1
        run = j - i
        if run >= 2:
            out.append(0x80 | run)
            out.append(c)
        else:
            out.append(c)
        i = j
    return bytes(out)

def byte_lines(data: bytes, indent: str = "        ") -> str:
    lines = []
    for k in range(0, len(data), 12):
        chunk = data[k:k+12]
        parts = []
        for b in chunk:
            if 0x20 <= b < 0x80 and chr(b) not in "\\'\"":
                parts.append(f"'{chr(b)}'")
            else:
                parts.append(f"${b:02X}")
        lines.append(f"{indent}.byte {','.join(parts)}")
    return "\n".join(lines)

def emit_level(n, lvl):
    w, h, ro, co, rows = lvl
    ascii_data = "".join(rows).encode("ascii")
    rle = rle_encode(ascii_data)
    header = bytes([w, h, ro, co])
    original_size = 4 + len(ascii_data)
    new_size = 4 + len(rle)
    comment = f"; level{n}  {w}x{h}  raw={len(ascii_data)}B  rle={len(rle)}B  (save {len(ascii_data)-len(rle)}B)"
    out = [comment]
    out.append(f"level{n}:")
    out.append(f"        .byte {w},{h},{ro},{co}")
    out.append(byte_lines(rle))
    return "\n".join(out), original_size, new_size

def main():
    txt = parse_levels(ROOT / "games" / "Sokoban.asm", 1, 47)
    hgr_ext = parse_levels(ROOT / "hgr" / "HGR6_Sokoban.asm", 48, 72)

    # Verify that levels 1..47 are identical across the three variants.
    tms = parse_levels(ROOT / "tms9918" / "TMS_Sokoban.asm", 1, 47)
    hgr1 = parse_levels(ROOT / "hgr" / "HGR6_Sokoban.asm", 1, 47)
    for n in range(1, 48):
        # Width/height/rows must match; TMS recomputes offsets so tolerate any.
        if (txt[n][0], txt[n][1], txt[n][4]) != (tms[n][0], tms[n][1], tms[n][4]):
            sys.exit(f"mismatch TXT vs TMS at level{n}")
        if txt[n] != hgr1[n]:
            sys.exit(f"mismatch TXT vs HGR at level{n}")

    # Write base levels (1..47)
    total_old = total_new = 0
    base_body = []
    for n in range(1, 48):
        blob, old, new = emit_level(n, txt[n])
        base_body.append(blob)
        total_old += old
        total_new += new
    base_text = (
        "; =============================================\n"
        "; sokoban_levels.inc - RLE-compressed levels 1..47\n"
        "; Auto-generated by tools/sokoban_rle.py. Do not edit.\n"
        "; Format: header (w, h, row_offset, col_offset) + RLE byte stream.\n"
        "; RLE: byte<$80 = literal; byte>=$80 -> (byte & $7F) copies of next byte.\n"
        "; =============================================\n\n"
        + "\n\n".join(base_body)
        + "\n"
    )
    (ROOT / "games" / "sokoban_levels.inc").write_text(base_text)

    # Write extended levels (48..72)
    total_old_e = total_new_e = 0
    ext_body = []
    for n in range(48, 73):
        blob, old, new = emit_level(n, hgr_ext[n])
        ext_body.append(blob)
        total_old_e += old
        total_new_e += new
    ext_text = (
        "; =============================================\n"
        "; sokoban_levels_ext.inc - RLE-compressed levels 48..72\n"
        "; Auto-generated by tools/sokoban_rle.py. Do not edit.\n"
        "; Format identical to sokoban_levels.inc.\n"
        "; =============================================\n\n"
        + "\n\n".join(ext_body)
        + "\n"
    )
    (ROOT / "games" / "sokoban_levels_ext.inc").write_text(ext_text)

    print(f"Base 1..47 : {total_old:5} -> {total_new:5} bytes  (save {total_old-total_new})")
    print(f"Ext  48..72: {total_old_e:5} -> {total_new_e:5} bytes  (save {total_old_e-total_new_e})")
    print(f"Combined   : {total_old+total_old_e:5} -> {total_new+total_new_e:5} bytes  (save {total_old+total_old_e-total_new-total_new_e})")

if __name__ == "__main__":
    main()
