#!/usr/bin/env python3
"""BBS auto-dial regression test — offline, with a fake BBS on 127.0.0.1.

What broke and why this exists
------------------------------
Loading ``software/NET/bbs.fozztexx.com.txt`` used to plug the Wi-Fi modem,
load the auto-dial program at $0280 and connect. After the topology/coordinator
refactor it stopped connecting: the load path commits any open card-configuration
transaction up front, ``CardConfigurationRequest::cards`` is an ABSOLUTE target
set, and a commit with nothing staged therefore requested the EMPTY machine —
sweeping the modem off the bus microseconds before the program started writing
to the ACIA at $B000. ``pom1::StagedCardConfiguration`` now carries the
"nothing staged" vs "stage no cards" distinction (``staged_card_configuration_smoke``
pins that logic); this test pins the user-visible end of it.

No Internet required, and none is used: phase A reads the shipped dumps as
text, phase B dials a listener this script owns on 127.0.0.1.

Phase A — the shipped assets
    Both ``bbs.*.com.txt`` dumps still load at $0280 and still carry a
    NUL-terminated ``ATDT <host>:23`` string. A dump that silently lost its
    load address or its dial string would "work" (POM1 loads it, the CPU runs)
    while connecting to nothing.

Phase B — load, run, dial, connect, once
    The SAME shipped program with only its dial target rewritten to the fake
    BBS runs on a real headless POM1. Asserts, in order: the loader reports
    run $0280; the modem logs a connection to the fake BBS; the emulated
    display shows the ATDT command echoed back and the modem's CONNECT; and
    the listener accepted EXACTLY ONE connection (a dial loop or a reconnect
    storm would show up as two).

Scope, stated plainly: the commit-with-nothing-staged decision lives in
``MainWindow_ImGui`` and no test binary links the UI, so this harness drives the
headless path — which builds its request once and never had the bug. It pins the
chain the user actually sees (dump -> $0280 -> ACIA -> socket); the decision that
broke is pinned by ``staged_card_configuration_smoke``. Neither test alone covers
both halves.

Skips (exit 77) when python3 or build/POM1 is missing, like the other harnesses.
"""

import argparse
import os
import re
import socket
import subprocess
import sys
import tempfile
import threading

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NET_DIR = os.path.join(REPO, "software", "NET")

# The auto-dial programs live at $0280 and the dial string is NUL-terminated —
# both are load-bearing, see the module docstring.
LOAD_ADDRESS = 0x0280

# 1.0227 MHz, so ~2 s of emulated time: the program sends the AT string at
# 9600 baud, the modem connects to a loopback socket, and CONNECT comes back.
RUN_CYCLES = 2_000_000


def skip(msg):
    print(f"SKIP: {msg}")
    sys.exit(77)


def fail(msg):
    print(f"FAIL: {msg}")
    sys.exit(1)


# --------------------------------------------------------------------------
# WOZMON hex dump: parse to a sparse byte image, emit back.
#
# Deliberately a strict, minimal reader — it accepts exactly what the shipped
# NET dumps use ("AAAA: HH HH ..." plus // comments) and nothing more, so a
# dump that drifts into another dialect fails here instead of being silently
# reinterpreted.
# --------------------------------------------------------------------------
def parse_wozmon_dump(path):
    image = {}
    first_addr = None
    with open(path, "r", encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.split("//", 1)[0].strip()
            if not line:
                continue
            m = re.match(r"^([0-9A-Fa-f]{1,4}):\s*(.*)$", line)
            if not m:
                fail(f"{os.path.basename(path)}:{lineno}: not an 'AAAA: HH ...' line: {line!r}")
            addr = int(m.group(1), 16)
            if first_addr is None:
                first_addr = addr
            for tok in m.group(2).split():
                if not re.fullmatch(r"[0-9A-Fa-f]{2}", tok):
                    fail(f"{os.path.basename(path)}:{lineno}: not a hex byte: {tok!r}")
                image[addr] = int(tok, 16)
                addr += 1
    return image, first_addr


def emit_wozmon_dump(image, path):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/test_bbs_autodial.py — do not edit.\n")
        for addr in sorted(image):
            if addr % 8 == 0 or addr - 1 not in image:
                fh.write(f"\n{addr:04X}:")
            fh.write(f" {image[addr]:02X}")
        fh.write("\n")


def find_dial_string(image):
    """Locate the NUL-terminated 'ATDT ...' string in a loaded image.

    Returns (start_address, text_without_terminators)."""
    text = {a: chr(b) for a, b in image.items() if 0x20 <= b < 0x7F}
    for addr in sorted(image):
        if "".join(text.get(addr + i, "\0") for i in range(4)) != "ATDT":
            continue
        out = []
        a = addr
        while a in image and image[a] != 0x00:
            out.append(image[a])
            a += 1
        if a not in image:
            fail(f"dial string at ${addr:04X} is not NUL-terminated")
        return addr, bytes(out).decode("ascii", "replace").rstrip("\r\n")
    return None, None


# --------------------------------------------------------------------------
# Phase A — the shipped dumps
# --------------------------------------------------------------------------
def check_shipped_dump(name):
    path = os.path.join(NET_DIR, name)
    if not os.path.isfile(path):
        fail(f"missing shipped auto-dial program: software/NET/{name}")
    image, first = parse_wozmon_dump(path)
    if first != LOAD_ADDRESS:
        fail(f"{name}: loads at ${first:04X}, expected ${LOAD_ADDRESS:04X}")
    addr, dial = find_dial_string(image)
    if addr is None:
        fail(f"{name}: no NUL-terminated ATDT string — it would load and dial nothing")
    if not re.fullmatch(r"ATDT [A-Za-z0-9.\-]+:\d+", dial):
        fail(f"{name}: malformed dial command {dial!r}")
    print(f"  ok  {name}: loads at ${first:04X}, dials {dial[5:]!r}")
    return image


# --------------------------------------------------------------------------
# Phase B — the fake BBS
# --------------------------------------------------------------------------
class FakeBBS:
    """A listener on 127.0.0.1 that counts connections. The 'connecteur factice'.

    Answers with a banner so the emulated Apple-1 has something to display, and
    keeps counting after the first accept so a dial loop is visible as N > 1.
    """

    def __init__(self):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.sock.bind(("127.0.0.1", 0))
        self.sock.listen(8)
        self.port = self.sock.getsockname()[1]
        self.connections = 0
        self._clients = []
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._serve, daemon=True)

    def __enter__(self):
        self._thread.start()
        return self

    def __exit__(self, *exc):
        self._stop.set()
        try:
            self.sock.close()
        except OSError:
            pass
        for c in self._clients:
            try:
                c.close()
            except OSError:
                pass
        self._thread.join(timeout=2)

    def _serve(self):
        self.sock.settimeout(0.25)
        while not self._stop.is_set():
            try:
                conn, _ = self.sock.accept()
            except (socket.timeout, OSError):
                continue
            self.connections += 1
            self._clients.append(conn)
            try:
                conn.sendall(b"\r\nPOM1 TEST BBS\r\n")
            except OSError:
                pass


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pom1", default=os.path.join(REPO, "build", "POM1"),
                    help="POM1 executable (default: build/POM1)")
    args = ap.parse_args()
    pom1 = args.pom1
    if not os.path.isfile(pom1) and not os.path.islink(pom1):
        skip(f"{pom1} not found")

    print("Phase A — shipped auto-dial programs")
    image = check_shipped_dump("bbs.fozztexx.com.txt")
    check_shipped_dump("bbs.retrocampus.com.txt")

    print("Phase B — load, run and dial a local fake BBS")
    with FakeBBS() as bbs:
        # Rewrite ONLY the dial target, so the program under test is the shipped
        # code. The string is NUL-terminated and the replacement is shorter, so
        # the trailing bytes of the original simply become unreachable.
        addr, original = find_dial_string(image)
        local = f"ATDT 127.0.0.1:{bbs.port}\r".encode("ascii")
        patched = dict(image)
        for i, byte in enumerate(local):
            patched[addr + i] = byte
        patched[addr + len(local)] = 0x00

        with tempfile.TemporaryDirectory() as tmp:
            dump = os.path.join(tmp, "bbs.local.txt")
            emit_wozmon_dump(patched, dump)
            cmd = [
                pom1, "--headless", "--enable", "wifi",
                "--load", f"{LOAD_ADDRESS:04X}:{dump}",
                "--exit-after-cycles", str(RUN_CYCLES),
            ]
            proc = subprocess.run(cmd, cwd=REPO, capture_output=True,
                                  text=True, encoding="utf-8", errors="replace",
                                  timeout=120)

        out = proc.stdout + proc.stderr
        if proc.returncode != 0:
            fail(f"POM1 exited {proc.returncode}\n{out}")
        for line in out.splitlines():
            if "ERROR" in line:
                fail(f"error in headless run: {line}\n{out}")

        # 1. The loader put the program where the dump says, and started it there.
        if f"run ${LOAD_ADDRESS:04X}" not in out:
            fail(f"program was not loaded to run at ${LOAD_ADDRESS:04X}\n{out}")

        # 2. The modem was on the bus and saw the ATDT the CPU wrote to $B000.
        #    Without the topology fix the card is detached here and this is the
        #    line that goes missing.
        if f"connecting to 127.0.0.1:{bbs.port}" not in out:
            fail(f"modem never dialled the fake BBS — was the card unplugged?\n{out}")

        # 3. What the Apple-1 actually displayed: the modem echoes the typed
        #    command back, then answers CONNECT once the socket is up.
        m = re.search(r"headless display capture: (.*)$", out, re.M)
        if not m:
            fail(f"no display capture in the headless run\n{out}")
        display = m.group(1)
        if "ATDT" not in display:
            fail(f"ATDT never reached the screen; display was {display!r}\n{out}")
        if "CONNECT" not in display:
            fail(f"modem never reported CONNECT; display was {display!r}\n{out}")

    # 4. Exactly one dial. Read after the listener is torn down so the counter
    #    has settled.
    if bbs.connections != 1:
        fail(f"expected exactly 1 connection attempt, fake BBS accepted {bbs.connections}")

    print(f"  ok  dialled 127.0.0.1:{bbs.port} once, CONNECT displayed")
    print(f"  ok  original shipped target was {original[5:]!r}")
    print("bbs_autodial: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
