# HGR7 Connect 4
PROJECT  := HGR7_Connect4
LOAD_CFG := ../../cc65/apple1_gen2.cfg
OUT_DIR  := ../../../software/hgr
LIB      := -I ../../lib/apple1 -I ../../lib/hgr -I ../../lib/m6502

include ../../cc65/Makefile.common
