; ============================================================================
; sprites_chess.asm  --  6 sprites (16x16, TMS9918 sprite/pattern mode)
; Generated by tools/build_chess_sprites.py from pic/chess_pieces_16x16.png.
; DO NOT EDIT BY HAND -- rerun the generator instead.
; ----------------------------------------------------------------------------
; One monochrome OUTLINE pattern per piece type (pawn,knight,bishop,
; rook,queen,king). The side colour (white/black) is set at render time via
; the TMS9918 colour table, so a single pattern serves both colours.
; Style 'outline': ink = the drawn outline + internal detail lines.
;
; Native TMS9918 16x16 layout: 32 bytes per piece -- first 16 = left half
; (col 0..7), next 16 = right half (col 8..15); MSB = leftmost pixel.
; ============================================================================
.export _chess_king_pat, _chess_queen_pat, _chess_bishop_pat, _chess_knight_pat, _chess_rook_pat, _chess_pawn_pat
.export chess_king_pat, chess_queen_pat, chess_bishop_pat, chess_knight_pat, chess_rook_pat, chess_pawn_pat

.segment "CODE"

; king (outline)
chess_king_pat:
_chess_king_pat:
        .byte $03, $06, $05, $1D, $22, $5D, $BE, $BE
        .byte $BE, $BF, $50, $2F, $20, $2F, $30, $1F
        .byte $C0, $60, $A0, $B8, $44, $BA, $7D, $7D
        .byte $7D, $FD, $0A, $F4, $04, $F4, $0C, $F8
; queen (outline)
chess_queen_pat:
_chess_queen_pat:
        .byte $01, $02, $82, $C5, $B5, $8B, $B7, $5F
        .byte $5F, $50, $2F, $20, $4F, $5F, $60, $1F
        .byte $80, $40, $41, $A3, $AD, $D1, $ED, $FA
        .byte $FA, $0A, $F4, $04, $F2, $FA, $06, $F8
; bishop (outline)
chess_bishop_pat:
_chess_bishop_pat:
        .byte $01, $02, $01, $02, $05, $0B, $17, $17
        .byte $17, $0B, $08, $0B, $05, $0B, $10, $1F
        .byte $80, $40, $80, $40, $A0, $D0, $A8, $68
        .byte $E8, $C8, $10, $D0, $A0, $D0, $08, $F8
; knight (outline)
chess_knight_pat:
_chess_knight_pat:
        .byte $02, $0B, $17, $2B, $57, $BC, $B2, $4E
        .byte $32, $05, $0B, $17, $17, $3F, $20, $3F
        .byte $40, $60, $D0, $E8, $68, $EC, $F4, $F4
        .byte $F4, $E8, $E8, $E8, $E8, $FC, $04, $FC
; rook (outline)
chess_rook_pat:
_chess_rook_pat:
        .byte $3D, $22, $29, $2F, $20, $17, $0B, $0B
        .byte $0B, $0B, $0B, $17, $10, $2F, $20, $3F
        .byte $BC, $44, $94, $F4, $04, $E8, $D0, $D0
        .byte $D0, $D0, $D0, $E8, $08, $F4, $04, $FC
; pawn (outline)
chess_pawn_pat:
_chess_pawn_pat:
        .byte $00, $01, $02, $05, $05, $02, $05, $05
        .byte $05, $0B, $17, $10, $1F, $10, $1F, $00
        .byte $00, $80, $40, $A0, $A0, $40, $A0, $A0
        .byte $A0, $D0, $E8, $08, $F8, $08, $F8, $00
