; ============================================================================
; sprites_chess.asm  --  6 sprites (16x16, TMS9918 sprite/pattern mode)
; Generated by tools/build_chess_sprites.py from pic/chess_pieces_16x16.png.
; DO NOT EDIT BY HAND -- rerun the generator instead.
; ----------------------------------------------------------------------------
; One monochrome SILHOUETTE pattern per piece type (pawn,knight,bishop,rook,
; queen,king). The side colour (white/black) is set at render time via the
; TMS9918 colour table, so a single pattern serves both colours.
;
; Native TMS9918 16x16 layout: 32 bytes per piece -- first 16 = left half
; (col 0..7), next 16 = right half (col 8..15); MSB = leftmost pixel.
; ============================================================================
.export _chess_pawn_pat, _chess_knight_pat, _chess_bishop_pat, _chess_rook_pat, _chess_queen_pat, _chess_king_pat
.export chess_pawn_pat, chess_knight_pat, chess_bishop_pat, chess_rook_pat, chess_queen_pat, chess_king_pat

.segment "CODE"

; pawn (silhouette)
chess_pawn_pat:
_chess_pawn_pat:
        .byte $03, $07, $07, $1F, $3F, $7F, $FF, $FF
        .byte $FF, $FF, $7F, $3F, $3F, $3F, $3F, $1F
        .byte $C0, $E0, $E0, $F8, $FC, $FE, $FF, $FF
        .byte $FF, $FF, $FE, $FC, $FC, $FC, $FC, $F8
; knight (silhouette)
chess_knight_pat:
_chess_knight_pat:
        .byte $01, $03, $83, $C7, $F7, $FF, $FF, $7F
        .byte $7F, $7F, $3F, $3F, $7F, $7F, $7F, $1F
        .byte $80, $C0, $C1, $E3, $EF, $FF, $FF, $FE
        .byte $FE, $FE, $FC, $FC, $FE, $FE, $FE, $F8
; bishop (silhouette)
chess_bishop_pat:
_chess_bishop_pat:
        .byte $01, $03, $01, $03, $07, $0F, $1F, $1F
        .byte $1F, $0F, $0F, $0F, $07, $0F, $1F, $1F
        .byte $80, $C0, $80, $C0, $E0, $F0, $F8, $F8
        .byte $F8, $F8, $F0, $F0, $E0, $F0, $F8, $F8
; rook (silhouette)
chess_rook_pat:
_chess_rook_pat:
        .byte $06, $0F, $1F, $3F, $7F, $FF, $FF, $7F
        .byte $33, $07, $0F, $1F, $1F, $3F, $3F, $3F
        .byte $C0, $E0, $F0, $F8, $F8, $FC, $FC, $FC
        .byte $FC, $F8, $F8, $F8, $F8, $FC, $FC, $FC
; queen (silhouette)
chess_queen_pat:
_chess_queen_pat:
        .byte $3D, $3F, $3F, $3F, $3F, $1F, $0F, $0F
        .byte $0F, $0F, $0F, $1F, $1F, $3F, $3F, $3F
        .byte $BC, $FC, $FC, $FC, $FC, $F8, $F0, $F0
        .byte $F0, $F0, $F0, $F8, $F8, $FC, $FC, $FC
; king (silhouette)
chess_king_pat:
_chess_king_pat:
        .byte $00, $01, $03, $07, $07, $03, $07, $07
        .byte $07, $0F, $1F, $1F, $1F, $1F, $1F, $00
        .byte $00, $80, $C0, $E0, $E0, $C0, $E0, $E0
        .byte $E0, $F0, $F8, $F8, $F8, $F8, $F8, $00
