# TMS9918 Maze 3D
PROJECT  := TMS_Maze3D
LOAD_CFG := apple1_maze3d.cfg
OUT_DIR  := ../../../software/Graphic TMS9918
LIB      := -I ../../lib/apple1 -I ../../lib/tms9918
EXTRA_ASM := ../../lib/tms9918/tms9918_pad.asm
EMIT_TXT := 1

include ../../cc65/Makefile.common
