# TMS9918 Orbital Pool
PROJECT  := TMS_OrbitalPool
LOAD_CFG := ../../cc65/apple1.cfg
OUT_DIR  := ../../../software/tms9918
LIB      := -I ../../lib/apple1
EMIT_TXT := 1

include ../../cc65/Makefile.common
