# TMS9918 Orbital Pool
PROJECT  := TMS_OrbitalPool
LOAD_CFG := ../../cc65/apple1_4k.cfg
OUT_DIR  := ../../../software/tms9918
LIB      := -I ../../lib/apple1 -I ../../lib/tms9918
EXTRA_ASM := ../../lib/tms9918/tms9918_pad.asm
EMIT_TXT := 1

include ../../cc65/Makefile.common
